
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  dfw_user: 'dfw_user',
  dfw_session: 'dfw_session',
  dfw_access: 'dfw_access',
  dfw_credential: 'dfw_credential',
  dfw_file: 'dfw_file'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Dfw_userScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  displayName: 'displayName',
  encodedKey: 'encodedKey',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type Dfw_userScalarFieldEnum = (typeof Dfw_userScalarFieldEnum)[keyof typeof Dfw_userScalarFieldEnum]


export const Dfw_sessionScalarFieldEnum = {
  id: 'id',
  agent: 'agent',
  ip: 'ip',
  idUser: 'idUser',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt'
} as const

export type Dfw_sessionScalarFieldEnum = (typeof Dfw_sessionScalarFieldEnum)[keyof typeof Dfw_sessionScalarFieldEnum]


export const Dfw_accessScalarFieldEnum = {
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type Dfw_accessScalarFieldEnum = (typeof Dfw_accessScalarFieldEnum)[keyof typeof Dfw_accessScalarFieldEnum]


export const Dfw_credentialScalarFieldEnum = {
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type Dfw_credentialScalarFieldEnum = (typeof Dfw_credentialScalarFieldEnum)[keyof typeof Dfw_credentialScalarFieldEnum]


export const Dfw_fileScalarFieldEnum = {
  id: 'id',
  name: 'name',
  path: 'path',
  url: 'url',
  variant: 'variant',
  size: 'size',
  checksum: 'checksum',
  mimetype: 'mimetype',
  storage: 'storage',
  expire: 'expire',
  metadata: 'metadata',
  idParent: 'idParent',
  idUser: 'idUser',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type Dfw_fileScalarFieldEnum = (typeof Dfw_fileScalarFieldEnum)[keyof typeof Dfw_fileScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull'
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

