
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model dfw_user
 * 
 */
export type dfw_user = Prisma.dfw_userModel
/**
 * Model dfw_session
 * 
 */
export type dfw_session = Prisma.dfw_sessionModel
/**
 * Model dfw_access
 * 
 */
export type dfw_access = Prisma.dfw_accessModel
/**
 * Model dfw_credential
 * 
 */
export type dfw_credential = Prisma.dfw_credentialModel
/**
 * Model dfw_file
 * 
 */
export type dfw_file = Prisma.dfw_fileModel
