
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const DFW_FILE_STORAGE = {
  LOCAL: 'LOCAL',
  EXTERNAL: 'EXTERNAL'
} as const

export type DFW_FILE_STORAGE = (typeof DFW_FILE_STORAGE)[keyof typeof DFW_FILE_STORAGE]
