
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dfw_file` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dfw_file
 * 
 */
export type dfw_fileModel = runtime.Types.Result.DefaultSelection<Prisma.$dfw_filePayload>

export type AggregateDfw_file = {
  _count: Dfw_fileCountAggregateOutputType | null
  _avg: Dfw_fileAvgAggregateOutputType | null
  _sum: Dfw_fileSumAggregateOutputType | null
  _min: Dfw_fileMinAggregateOutputType | null
  _max: Dfw_fileMaxAggregateOutputType | null
}

export type Dfw_fileAvgAggregateOutputType = {
  size: number | null
}

export type Dfw_fileSumAggregateOutputType = {
  size: number | null
}

export type Dfw_fileMinAggregateOutputType = {
  id: string | null
  name: string | null
  path: string | null
  url: string | null
  variant: string | null
  size: number | null
  checksum: string | null
  mimetype: string | null
  storage: $Enums.DFW_FILE_STORAGE | null
  expire: Date | null
  idParent: string | null
  idUser: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Dfw_fileMaxAggregateOutputType = {
  id: string | null
  name: string | null
  path: string | null
  url: string | null
  variant: string | null
  size: number | null
  checksum: string | null
  mimetype: string | null
  storage: $Enums.DFW_FILE_STORAGE | null
  expire: Date | null
  idParent: string | null
  idUser: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Dfw_fileCountAggregateOutputType = {
  id: number
  name: number
  path: number
  url: number
  variant: number
  size: number
  checksum: number
  mimetype: number
  storage: number
  expire: number
  metadata: number
  idParent: number
  idUser: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type Dfw_fileAvgAggregateInputType = {
  size?: true
}

export type Dfw_fileSumAggregateInputType = {
  size?: true
}

export type Dfw_fileMinAggregateInputType = {
  id?: true
  name?: true
  path?: true
  url?: true
  variant?: true
  size?: true
  checksum?: true
  mimetype?: true
  storage?: true
  expire?: true
  idParent?: true
  idUser?: true
  createdAt?: true
  updatedAt?: true
}

export type Dfw_fileMaxAggregateInputType = {
  id?: true
  name?: true
  path?: true
  url?: true
  variant?: true
  size?: true
  checksum?: true
  mimetype?: true
  storage?: true
  expire?: true
  idParent?: true
  idUser?: true
  createdAt?: true
  updatedAt?: true
}

export type Dfw_fileCountAggregateInputType = {
  id?: true
  name?: true
  path?: true
  url?: true
  variant?: true
  size?: true
  checksum?: true
  mimetype?: true
  storage?: true
  expire?: true
  metadata?: true
  idParent?: true
  idUser?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type Dfw_fileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dfw_file to aggregate.
   */
  where?: Prisma.dfw_fileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_files to fetch.
   */
  orderBy?: Prisma.dfw_fileOrderByWithRelationInput | Prisma.dfw_fileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dfw_fileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dfw_files
  **/
  _count?: true | Dfw_fileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Dfw_fileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Dfw_fileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Dfw_fileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Dfw_fileMaxAggregateInputType
}

export type GetDfw_fileAggregateType<T extends Dfw_fileAggregateArgs> = {
      [P in keyof T & keyof AggregateDfw_file]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDfw_file[P]>
    : Prisma.GetScalarType<T[P], AggregateDfw_file[P]>
}




export type dfw_fileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_fileWhereInput
  orderBy?: Prisma.dfw_fileOrderByWithAggregationInput | Prisma.dfw_fileOrderByWithAggregationInput[]
  by: Prisma.Dfw_fileScalarFieldEnum[] | Prisma.Dfw_fileScalarFieldEnum
  having?: Prisma.dfw_fileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Dfw_fileCountAggregateInputType | true
  _avg?: Dfw_fileAvgAggregateInputType
  _sum?: Dfw_fileSumAggregateInputType
  _min?: Dfw_fileMinAggregateInputType
  _max?: Dfw_fileMaxAggregateInputType
}

export type Dfw_fileGroupByOutputType = {
  id: string
  name: string | null
  path: string | null
  url: string | null
  variant: string | null
  size: number | null
  checksum: string | null
  mimetype: string | null
  storage: $Enums.DFW_FILE_STORAGE
  expire: Date | null
  metadata: runtime.JsonValue | null
  idParent: string | null
  idUser: string | null
  createdAt: Date
  updatedAt: Date
  _count: Dfw_fileCountAggregateOutputType | null
  _avg: Dfw_fileAvgAggregateOutputType | null
  _sum: Dfw_fileSumAggregateOutputType | null
  _min: Dfw_fileMinAggregateOutputType | null
  _max: Dfw_fileMaxAggregateOutputType | null
}

type GetDfw_fileGroupByPayload<T extends dfw_fileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Dfw_fileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Dfw_fileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Dfw_fileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Dfw_fileGroupByOutputType[P]>
      }
    >
  >



export type dfw_fileWhereInput = {
  AND?: Prisma.dfw_fileWhereInput | Prisma.dfw_fileWhereInput[]
  OR?: Prisma.dfw_fileWhereInput[]
  NOT?: Prisma.dfw_fileWhereInput | Prisma.dfw_fileWhereInput[]
  id?: Prisma.StringFilter<"dfw_file"> | string
  name?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  path?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  url?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  variant?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  size?: Prisma.IntNullableFilter<"dfw_file"> | number | null
  checksum?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  mimetype?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFilter<"dfw_file"> | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.DateTimeNullableFilter<"dfw_file"> | Date | string | null
  metadata?: Prisma.JsonNullableFilter<"dfw_file">
  idParent?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  idUser?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_file"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_file"> | Date | string
  user?: Prisma.XOR<Prisma.Dfw_userNullableScalarRelationFilter, Prisma.dfw_userWhereInput> | null
  parent?: Prisma.XOR<Prisma.Dfw_fileNullableScalarRelationFilter, Prisma.dfw_fileWhereInput> | null
  children?: Prisma.Dfw_fileListRelationFilter
}

export type dfw_fileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  path?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrderInput | Prisma.SortOrder
  variant?: Prisma.SortOrderInput | Prisma.SortOrder
  size?: Prisma.SortOrderInput | Prisma.SortOrder
  checksum?: Prisma.SortOrderInput | Prisma.SortOrder
  mimetype?: Prisma.SortOrderInput | Prisma.SortOrder
  storage?: Prisma.SortOrder
  expire?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  idParent?: Prisma.SortOrderInput | Prisma.SortOrder
  idUser?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.dfw_userOrderByWithRelationInput
  parent?: Prisma.dfw_fileOrderByWithRelationInput
  children?: Prisma.dfw_fileOrderByRelationAggregateInput
}

export type dfw_fileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.dfw_fileWhereInput | Prisma.dfw_fileWhereInput[]
  OR?: Prisma.dfw_fileWhereInput[]
  NOT?: Prisma.dfw_fileWhereInput | Prisma.dfw_fileWhereInput[]
  name?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  path?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  url?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  variant?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  size?: Prisma.IntNullableFilter<"dfw_file"> | number | null
  checksum?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  mimetype?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFilter<"dfw_file"> | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.DateTimeNullableFilter<"dfw_file"> | Date | string | null
  metadata?: Prisma.JsonNullableFilter<"dfw_file">
  idParent?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  idUser?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_file"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_file"> | Date | string
  user?: Prisma.XOR<Prisma.Dfw_userNullableScalarRelationFilter, Prisma.dfw_userWhereInput> | null
  parent?: Prisma.XOR<Prisma.Dfw_fileNullableScalarRelationFilter, Prisma.dfw_fileWhereInput> | null
  children?: Prisma.Dfw_fileListRelationFilter
}, "id">

export type dfw_fileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  path?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrderInput | Prisma.SortOrder
  variant?: Prisma.SortOrderInput | Prisma.SortOrder
  size?: Prisma.SortOrderInput | Prisma.SortOrder
  checksum?: Prisma.SortOrderInput | Prisma.SortOrder
  mimetype?: Prisma.SortOrderInput | Prisma.SortOrder
  storage?: Prisma.SortOrder
  expire?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  idParent?: Prisma.SortOrderInput | Prisma.SortOrder
  idUser?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.dfw_fileCountOrderByAggregateInput
  _avg?: Prisma.dfw_fileAvgOrderByAggregateInput
  _max?: Prisma.dfw_fileMaxOrderByAggregateInput
  _min?: Prisma.dfw_fileMinOrderByAggregateInput
  _sum?: Prisma.dfw_fileSumOrderByAggregateInput
}

export type dfw_fileScalarWhereWithAggregatesInput = {
  AND?: Prisma.dfw_fileScalarWhereWithAggregatesInput | Prisma.dfw_fileScalarWhereWithAggregatesInput[]
  OR?: Prisma.dfw_fileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dfw_fileScalarWhereWithAggregatesInput | Prisma.dfw_fileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"dfw_file"> | string
  name?: Prisma.StringNullableWithAggregatesFilter<"dfw_file"> | string | null
  path?: Prisma.StringNullableWithAggregatesFilter<"dfw_file"> | string | null
  url?: Prisma.StringNullableWithAggregatesFilter<"dfw_file"> | string | null
  variant?: Prisma.StringNullableWithAggregatesFilter<"dfw_file"> | string | null
  size?: Prisma.IntNullableWithAggregatesFilter<"dfw_file"> | number | null
  checksum?: Prisma.StringNullableWithAggregatesFilter<"dfw_file"> | string | null
  mimetype?: Prisma.StringNullableWithAggregatesFilter<"dfw_file"> | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEWithAggregatesFilter<"dfw_file"> | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.DateTimeNullableWithAggregatesFilter<"dfw_file"> | Date | string | null
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"dfw_file">
  idParent?: Prisma.StringNullableWithAggregatesFilter<"dfw_file"> | string | null
  idUser?: Prisma.StringNullableWithAggregatesFilter<"dfw_file"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"dfw_file"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"dfw_file"> | Date | string
}

export type dfw_fileCreateInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.dfw_userCreateNestedOneWithoutFilesInput
  parent?: Prisma.dfw_fileCreateNestedOneWithoutChildrenInput
  children?: Prisma.dfw_fileCreateNestedManyWithoutParentInput
}

export type dfw_fileUncheckedCreateInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idParent?: string | null
  idUser?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.dfw_fileUncheckedCreateNestedManyWithoutParentInput
}

export type dfw_fileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.dfw_userUpdateOneWithoutFilesNestedInput
  parent?: Prisma.dfw_fileUpdateOneWithoutChildrenNestedInput
  children?: Prisma.dfw_fileUpdateManyWithoutParentNestedInput
}

export type dfw_fileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idParent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  idUser?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.dfw_fileUncheckedUpdateManyWithoutParentNestedInput
}

export type dfw_fileCreateManyInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idParent?: string | null
  idUser?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type dfw_fileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_fileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idParent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  idUser?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Dfw_fileListRelationFilter = {
  every?: Prisma.dfw_fileWhereInput
  some?: Prisma.dfw_fileWhereInput
  none?: Prisma.dfw_fileWhereInput
}

export type dfw_fileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Dfw_fileNullableScalarRelationFilter = {
  is?: Prisma.dfw_fileWhereInput | null
  isNot?: Prisma.dfw_fileWhereInput | null
}

export type dfw_fileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  path?: Prisma.SortOrder
  url?: Prisma.SortOrder
  variant?: Prisma.SortOrder
  size?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  mimetype?: Prisma.SortOrder
  storage?: Prisma.SortOrder
  expire?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  idParent?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type dfw_fileAvgOrderByAggregateInput = {
  size?: Prisma.SortOrder
}

export type dfw_fileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  path?: Prisma.SortOrder
  url?: Prisma.SortOrder
  variant?: Prisma.SortOrder
  size?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  mimetype?: Prisma.SortOrder
  storage?: Prisma.SortOrder
  expire?: Prisma.SortOrder
  idParent?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type dfw_fileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  path?: Prisma.SortOrder
  url?: Prisma.SortOrder
  variant?: Prisma.SortOrder
  size?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  mimetype?: Prisma.SortOrder
  storage?: Prisma.SortOrder
  expire?: Prisma.SortOrder
  idParent?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type dfw_fileSumOrderByAggregateInput = {
  size?: Prisma.SortOrder
}

export type dfw_fileCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.dfw_fileCreateWithoutUserInput, Prisma.dfw_fileUncheckedCreateWithoutUserInput> | Prisma.dfw_fileCreateWithoutUserInput[] | Prisma.dfw_fileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.dfw_fileCreateOrConnectWithoutUserInput | Prisma.dfw_fileCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.dfw_fileCreateManyUserInputEnvelope
  connect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
}

export type dfw_fileUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.dfw_fileCreateWithoutUserInput, Prisma.dfw_fileUncheckedCreateWithoutUserInput> | Prisma.dfw_fileCreateWithoutUserInput[] | Prisma.dfw_fileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.dfw_fileCreateOrConnectWithoutUserInput | Prisma.dfw_fileCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.dfw_fileCreateManyUserInputEnvelope
  connect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
}

export type dfw_fileUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_fileCreateWithoutUserInput, Prisma.dfw_fileUncheckedCreateWithoutUserInput> | Prisma.dfw_fileCreateWithoutUserInput[] | Prisma.dfw_fileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.dfw_fileCreateOrConnectWithoutUserInput | Prisma.dfw_fileCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.dfw_fileUpsertWithWhereUniqueWithoutUserInput | Prisma.dfw_fileUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.dfw_fileCreateManyUserInputEnvelope
  set?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  disconnect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  delete?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  connect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  update?: Prisma.dfw_fileUpdateWithWhereUniqueWithoutUserInput | Prisma.dfw_fileUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.dfw_fileUpdateManyWithWhereWithoutUserInput | Prisma.dfw_fileUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.dfw_fileScalarWhereInput | Prisma.dfw_fileScalarWhereInput[]
}

export type dfw_fileUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_fileCreateWithoutUserInput, Prisma.dfw_fileUncheckedCreateWithoutUserInput> | Prisma.dfw_fileCreateWithoutUserInput[] | Prisma.dfw_fileUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.dfw_fileCreateOrConnectWithoutUserInput | Prisma.dfw_fileCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.dfw_fileUpsertWithWhereUniqueWithoutUserInput | Prisma.dfw_fileUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.dfw_fileCreateManyUserInputEnvelope
  set?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  disconnect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  delete?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  connect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  update?: Prisma.dfw_fileUpdateWithWhereUniqueWithoutUserInput | Prisma.dfw_fileUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.dfw_fileUpdateManyWithWhereWithoutUserInput | Prisma.dfw_fileUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.dfw_fileScalarWhereInput | Prisma.dfw_fileScalarWhereInput[]
}

export type dfw_fileCreateNestedOneWithoutChildrenInput = {
  create?: Prisma.XOR<Prisma.dfw_fileCreateWithoutChildrenInput, Prisma.dfw_fileUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.dfw_fileCreateOrConnectWithoutChildrenInput
  connect?: Prisma.dfw_fileWhereUniqueInput
}

export type dfw_fileCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.dfw_fileCreateWithoutParentInput, Prisma.dfw_fileUncheckedCreateWithoutParentInput> | Prisma.dfw_fileCreateWithoutParentInput[] | Prisma.dfw_fileUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.dfw_fileCreateOrConnectWithoutParentInput | Prisma.dfw_fileCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.dfw_fileCreateManyParentInputEnvelope
  connect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
}

export type dfw_fileUncheckedCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.dfw_fileCreateWithoutParentInput, Prisma.dfw_fileUncheckedCreateWithoutParentInput> | Prisma.dfw_fileCreateWithoutParentInput[] | Prisma.dfw_fileUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.dfw_fileCreateOrConnectWithoutParentInput | Prisma.dfw_fileCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.dfw_fileCreateManyParentInputEnvelope
  connect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EnumDFW_FILE_STORAGEFieldUpdateOperationsInput = {
  set?: $Enums.DFW_FILE_STORAGE
}

export type dfw_fileUpdateOneWithoutChildrenNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_fileCreateWithoutChildrenInput, Prisma.dfw_fileUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.dfw_fileCreateOrConnectWithoutChildrenInput
  upsert?: Prisma.dfw_fileUpsertWithoutChildrenInput
  disconnect?: Prisma.dfw_fileWhereInput | boolean
  delete?: Prisma.dfw_fileWhereInput | boolean
  connect?: Prisma.dfw_fileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.dfw_fileUpdateToOneWithWhereWithoutChildrenInput, Prisma.dfw_fileUpdateWithoutChildrenInput>, Prisma.dfw_fileUncheckedUpdateWithoutChildrenInput>
}

export type dfw_fileUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_fileCreateWithoutParentInput, Prisma.dfw_fileUncheckedCreateWithoutParentInput> | Prisma.dfw_fileCreateWithoutParentInput[] | Prisma.dfw_fileUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.dfw_fileCreateOrConnectWithoutParentInput | Prisma.dfw_fileCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.dfw_fileUpsertWithWhereUniqueWithoutParentInput | Prisma.dfw_fileUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.dfw_fileCreateManyParentInputEnvelope
  set?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  disconnect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  delete?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  connect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  update?: Prisma.dfw_fileUpdateWithWhereUniqueWithoutParentInput | Prisma.dfw_fileUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.dfw_fileUpdateManyWithWhereWithoutParentInput | Prisma.dfw_fileUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.dfw_fileScalarWhereInput | Prisma.dfw_fileScalarWhereInput[]
}

export type dfw_fileUncheckedUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_fileCreateWithoutParentInput, Prisma.dfw_fileUncheckedCreateWithoutParentInput> | Prisma.dfw_fileCreateWithoutParentInput[] | Prisma.dfw_fileUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.dfw_fileCreateOrConnectWithoutParentInput | Prisma.dfw_fileCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.dfw_fileUpsertWithWhereUniqueWithoutParentInput | Prisma.dfw_fileUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.dfw_fileCreateManyParentInputEnvelope
  set?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  disconnect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  delete?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  connect?: Prisma.dfw_fileWhereUniqueInput | Prisma.dfw_fileWhereUniqueInput[]
  update?: Prisma.dfw_fileUpdateWithWhereUniqueWithoutParentInput | Prisma.dfw_fileUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.dfw_fileUpdateManyWithWhereWithoutParentInput | Prisma.dfw_fileUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.dfw_fileScalarWhereInput | Prisma.dfw_fileScalarWhereInput[]
}

export type dfw_fileCreateWithoutUserInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.dfw_fileCreateNestedOneWithoutChildrenInput
  children?: Prisma.dfw_fileCreateNestedManyWithoutParentInput
}

export type dfw_fileUncheckedCreateWithoutUserInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idParent?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.dfw_fileUncheckedCreateNestedManyWithoutParentInput
}

export type dfw_fileCreateOrConnectWithoutUserInput = {
  where: Prisma.dfw_fileWhereUniqueInput
  create: Prisma.XOR<Prisma.dfw_fileCreateWithoutUserInput, Prisma.dfw_fileUncheckedCreateWithoutUserInput>
}

export type dfw_fileCreateManyUserInputEnvelope = {
  data: Prisma.dfw_fileCreateManyUserInput | Prisma.dfw_fileCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type dfw_fileUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.dfw_fileWhereUniqueInput
  update: Prisma.XOR<Prisma.dfw_fileUpdateWithoutUserInput, Prisma.dfw_fileUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.dfw_fileCreateWithoutUserInput, Prisma.dfw_fileUncheckedCreateWithoutUserInput>
}

export type dfw_fileUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.dfw_fileWhereUniqueInput
  data: Prisma.XOR<Prisma.dfw_fileUpdateWithoutUserInput, Prisma.dfw_fileUncheckedUpdateWithoutUserInput>
}

export type dfw_fileUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.dfw_fileScalarWhereInput
  data: Prisma.XOR<Prisma.dfw_fileUpdateManyMutationInput, Prisma.dfw_fileUncheckedUpdateManyWithoutUserInput>
}

export type dfw_fileScalarWhereInput = {
  AND?: Prisma.dfw_fileScalarWhereInput | Prisma.dfw_fileScalarWhereInput[]
  OR?: Prisma.dfw_fileScalarWhereInput[]
  NOT?: Prisma.dfw_fileScalarWhereInput | Prisma.dfw_fileScalarWhereInput[]
  id?: Prisma.StringFilter<"dfw_file"> | string
  name?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  path?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  url?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  variant?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  size?: Prisma.IntNullableFilter<"dfw_file"> | number | null
  checksum?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  mimetype?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFilter<"dfw_file"> | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.DateTimeNullableFilter<"dfw_file"> | Date | string | null
  metadata?: Prisma.JsonNullableFilter<"dfw_file">
  idParent?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  idUser?: Prisma.StringNullableFilter<"dfw_file"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_file"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_file"> | Date | string
}

export type dfw_fileCreateWithoutChildrenInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.dfw_userCreateNestedOneWithoutFilesInput
  parent?: Prisma.dfw_fileCreateNestedOneWithoutChildrenInput
}

export type dfw_fileUncheckedCreateWithoutChildrenInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idParent?: string | null
  idUser?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type dfw_fileCreateOrConnectWithoutChildrenInput = {
  where: Prisma.dfw_fileWhereUniqueInput
  create: Prisma.XOR<Prisma.dfw_fileCreateWithoutChildrenInput, Prisma.dfw_fileUncheckedCreateWithoutChildrenInput>
}

export type dfw_fileCreateWithoutParentInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.dfw_userCreateNestedOneWithoutFilesInput
  children?: Prisma.dfw_fileCreateNestedManyWithoutParentInput
}

export type dfw_fileUncheckedCreateWithoutParentInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idUser?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.dfw_fileUncheckedCreateNestedManyWithoutParentInput
}

export type dfw_fileCreateOrConnectWithoutParentInput = {
  where: Prisma.dfw_fileWhereUniqueInput
  create: Prisma.XOR<Prisma.dfw_fileCreateWithoutParentInput, Prisma.dfw_fileUncheckedCreateWithoutParentInput>
}

export type dfw_fileCreateManyParentInputEnvelope = {
  data: Prisma.dfw_fileCreateManyParentInput | Prisma.dfw_fileCreateManyParentInput[]
  skipDuplicates?: boolean
}

export type dfw_fileUpsertWithoutChildrenInput = {
  update: Prisma.XOR<Prisma.dfw_fileUpdateWithoutChildrenInput, Prisma.dfw_fileUncheckedUpdateWithoutChildrenInput>
  create: Prisma.XOR<Prisma.dfw_fileCreateWithoutChildrenInput, Prisma.dfw_fileUncheckedCreateWithoutChildrenInput>
  where?: Prisma.dfw_fileWhereInput
}

export type dfw_fileUpdateToOneWithWhereWithoutChildrenInput = {
  where?: Prisma.dfw_fileWhereInput
  data: Prisma.XOR<Prisma.dfw_fileUpdateWithoutChildrenInput, Prisma.dfw_fileUncheckedUpdateWithoutChildrenInput>
}

export type dfw_fileUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.dfw_userUpdateOneWithoutFilesNestedInput
  parent?: Prisma.dfw_fileUpdateOneWithoutChildrenNestedInput
}

export type dfw_fileUncheckedUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idParent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  idUser?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_fileUpsertWithWhereUniqueWithoutParentInput = {
  where: Prisma.dfw_fileWhereUniqueInput
  update: Prisma.XOR<Prisma.dfw_fileUpdateWithoutParentInput, Prisma.dfw_fileUncheckedUpdateWithoutParentInput>
  create: Prisma.XOR<Prisma.dfw_fileCreateWithoutParentInput, Prisma.dfw_fileUncheckedCreateWithoutParentInput>
}

export type dfw_fileUpdateWithWhereUniqueWithoutParentInput = {
  where: Prisma.dfw_fileWhereUniqueInput
  data: Prisma.XOR<Prisma.dfw_fileUpdateWithoutParentInput, Prisma.dfw_fileUncheckedUpdateWithoutParentInput>
}

export type dfw_fileUpdateManyWithWhereWithoutParentInput = {
  where: Prisma.dfw_fileScalarWhereInput
  data: Prisma.XOR<Prisma.dfw_fileUpdateManyMutationInput, Prisma.dfw_fileUncheckedUpdateManyWithoutParentInput>
}

export type dfw_fileCreateManyUserInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idParent?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type dfw_fileUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.dfw_fileUpdateOneWithoutChildrenNestedInput
  children?: Prisma.dfw_fileUpdateManyWithoutParentNestedInput
}

export type dfw_fileUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idParent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.dfw_fileUncheckedUpdateManyWithoutParentNestedInput
}

export type dfw_fileUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idParent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_fileCreateManyParentInput = {
  id?: string
  name?: string | null
  path?: string | null
  url?: string | null
  variant?: string | null
  size?: number | null
  checksum?: string | null
  mimetype?: string | null
  storage?: $Enums.DFW_FILE_STORAGE
  expire?: Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idUser?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type dfw_fileUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.dfw_userUpdateOneWithoutFilesNestedInput
  children?: Prisma.dfw_fileUpdateManyWithoutParentNestedInput
}

export type dfw_fileUncheckedUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idUser?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.dfw_fileUncheckedUpdateManyWithoutParentNestedInput
}

export type dfw_fileUncheckedUpdateManyWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  path?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mimetype?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storage?: Prisma.EnumDFW_FILE_STORAGEFieldUpdateOperationsInput | $Enums.DFW_FILE_STORAGE
  expire?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  idUser?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type Dfw_fileCountOutputType
 */

export type Dfw_fileCountOutputType = {
  children: number
}

export type Dfw_fileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  children?: boolean | Dfw_fileCountOutputTypeCountChildrenArgs
}

/**
 * Dfw_fileCountOutputType without action
 */
export type Dfw_fileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dfw_fileCountOutputType
   */
  select?: Prisma.Dfw_fileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Dfw_fileCountOutputType without action
 */
export type Dfw_fileCountOutputTypeCountChildrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_fileWhereInput
}


export type dfw_fileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  path?: boolean
  url?: boolean
  variant?: boolean
  size?: boolean
  checksum?: boolean
  mimetype?: boolean
  storage?: boolean
  expire?: boolean
  metadata?: boolean
  idParent?: boolean
  idUser?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.dfw_file$userArgs<ExtArgs>
  parent?: boolean | Prisma.dfw_file$parentArgs<ExtArgs>
  children?: boolean | Prisma.dfw_file$childrenArgs<ExtArgs>
  _count?: boolean | Prisma.Dfw_fileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dfw_file"]>

export type dfw_fileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  path?: boolean
  url?: boolean
  variant?: boolean
  size?: boolean
  checksum?: boolean
  mimetype?: boolean
  storage?: boolean
  expire?: boolean
  metadata?: boolean
  idParent?: boolean
  idUser?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.dfw_file$userArgs<ExtArgs>
  parent?: boolean | Prisma.dfw_file$parentArgs<ExtArgs>
}, ExtArgs["result"]["dfw_file"]>

export type dfw_fileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  path?: boolean
  url?: boolean
  variant?: boolean
  size?: boolean
  checksum?: boolean
  mimetype?: boolean
  storage?: boolean
  expire?: boolean
  metadata?: boolean
  idParent?: boolean
  idUser?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.dfw_file$userArgs<ExtArgs>
  parent?: boolean | Prisma.dfw_file$parentArgs<ExtArgs>
}, ExtArgs["result"]["dfw_file"]>

export type dfw_fileSelectScalar = {
  id?: boolean
  name?: boolean
  path?: boolean
  url?: boolean
  variant?: boolean
  size?: boolean
  checksum?: boolean
  mimetype?: boolean
  storage?: boolean
  expire?: boolean
  metadata?: boolean
  idParent?: boolean
  idUser?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type dfw_fileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "path" | "url" | "variant" | "size" | "checksum" | "mimetype" | "storage" | "expire" | "metadata" | "idParent" | "idUser" | "createdAt" | "updatedAt", ExtArgs["result"]["dfw_file"]>
export type dfw_fileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.dfw_file$userArgs<ExtArgs>
  parent?: boolean | Prisma.dfw_file$parentArgs<ExtArgs>
  children?: boolean | Prisma.dfw_file$childrenArgs<ExtArgs>
  _count?: boolean | Prisma.Dfw_fileCountOutputTypeDefaultArgs<ExtArgs>
}
export type dfw_fileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.dfw_file$userArgs<ExtArgs>
  parent?: boolean | Prisma.dfw_file$parentArgs<ExtArgs>
}
export type dfw_fileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.dfw_file$userArgs<ExtArgs>
  parent?: boolean | Prisma.dfw_file$parentArgs<ExtArgs>
}

export type $dfw_filePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dfw_file"
  objects: {
    user: Prisma.$dfw_userPayload<ExtArgs> | null
    parent: Prisma.$dfw_filePayload<ExtArgs> | null
    children: Prisma.$dfw_filePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string | null
    path: string | null
    url: string | null
    variant: string | null
    size: number | null
    checksum: string | null
    mimetype: string | null
    storage: $Enums.DFW_FILE_STORAGE
    expire: Date | null
    metadata: runtime.JsonValue | null
    idParent: string | null
    idUser: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dfw_file"]>
  composites: {}
}

export type dfw_fileGetPayload<S extends boolean | null | undefined | dfw_fileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dfw_filePayload, S>

export type dfw_fileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dfw_fileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Dfw_fileCountAggregateInputType | true
  }

export interface dfw_fileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dfw_file'], meta: { name: 'dfw_file' } }
  /**
   * Find zero or one Dfw_file that matches the filter.
   * @param {dfw_fileFindUniqueArgs} args - Arguments to find a Dfw_file
   * @example
   * // Get one Dfw_file
   * const dfw_file = await prisma.dfw_file.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dfw_fileFindUniqueArgs>(args: Prisma.SelectSubset<T, dfw_fileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dfw_fileClient<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dfw_file that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dfw_fileFindUniqueOrThrowArgs} args - Arguments to find a Dfw_file
   * @example
   * // Get one Dfw_file
   * const dfw_file = await prisma.dfw_file.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dfw_fileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dfw_fileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dfw_fileClient<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dfw_file that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_fileFindFirstArgs} args - Arguments to find a Dfw_file
   * @example
   * // Get one Dfw_file
   * const dfw_file = await prisma.dfw_file.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dfw_fileFindFirstArgs>(args?: Prisma.SelectSubset<T, dfw_fileFindFirstArgs<ExtArgs>>): Prisma.Prisma__dfw_fileClient<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dfw_file that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_fileFindFirstOrThrowArgs} args - Arguments to find a Dfw_file
   * @example
   * // Get one Dfw_file
   * const dfw_file = await prisma.dfw_file.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dfw_fileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dfw_fileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dfw_fileClient<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Dfw_files that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_fileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Dfw_files
   * const dfw_files = await prisma.dfw_file.findMany()
   * 
   * // Get first 10 Dfw_files
   * const dfw_files = await prisma.dfw_file.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dfw_fileWithIdOnly = await prisma.dfw_file.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends dfw_fileFindManyArgs>(args?: Prisma.SelectSubset<T, dfw_fileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dfw_file.
   * @param {dfw_fileCreateArgs} args - Arguments to create a Dfw_file.
   * @example
   * // Create one Dfw_file
   * const Dfw_file = await prisma.dfw_file.create({
   *   data: {
   *     // ... data to create a Dfw_file
   *   }
   * })
   * 
   */
  create<T extends dfw_fileCreateArgs>(args: Prisma.SelectSubset<T, dfw_fileCreateArgs<ExtArgs>>): Prisma.Prisma__dfw_fileClient<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Dfw_files.
   * @param {dfw_fileCreateManyArgs} args - Arguments to create many Dfw_files.
   * @example
   * // Create many Dfw_files
   * const dfw_file = await prisma.dfw_file.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dfw_fileCreateManyArgs>(args?: Prisma.SelectSubset<T, dfw_fileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Dfw_files and returns the data saved in the database.
   * @param {dfw_fileCreateManyAndReturnArgs} args - Arguments to create many Dfw_files.
   * @example
   * // Create many Dfw_files
   * const dfw_file = await prisma.dfw_file.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Dfw_files and only return the `id`
   * const dfw_fileWithIdOnly = await prisma.dfw_file.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends dfw_fileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, dfw_fileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Dfw_file.
   * @param {dfw_fileDeleteArgs} args - Arguments to delete one Dfw_file.
   * @example
   * // Delete one Dfw_file
   * const Dfw_file = await prisma.dfw_file.delete({
   *   where: {
   *     // ... filter to delete one Dfw_file
   *   }
   * })
   * 
   */
  delete<T extends dfw_fileDeleteArgs>(args: Prisma.SelectSubset<T, dfw_fileDeleteArgs<ExtArgs>>): Prisma.Prisma__dfw_fileClient<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dfw_file.
   * @param {dfw_fileUpdateArgs} args - Arguments to update one Dfw_file.
   * @example
   * // Update one Dfw_file
   * const dfw_file = await prisma.dfw_file.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dfw_fileUpdateArgs>(args: Prisma.SelectSubset<T, dfw_fileUpdateArgs<ExtArgs>>): Prisma.Prisma__dfw_fileClient<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Dfw_files.
   * @param {dfw_fileDeleteManyArgs} args - Arguments to filter Dfw_files to delete.
   * @example
   * // Delete a few Dfw_files
   * const { count } = await prisma.dfw_file.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dfw_fileDeleteManyArgs>(args?: Prisma.SelectSubset<T, dfw_fileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dfw_files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_fileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Dfw_files
   * const dfw_file = await prisma.dfw_file.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dfw_fileUpdateManyArgs>(args: Prisma.SelectSubset<T, dfw_fileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dfw_files and returns the data updated in the database.
   * @param {dfw_fileUpdateManyAndReturnArgs} args - Arguments to update many Dfw_files.
   * @example
   * // Update many Dfw_files
   * const dfw_file = await prisma.dfw_file.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Dfw_files and only return the `id`
   * const dfw_fileWithIdOnly = await prisma.dfw_file.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends dfw_fileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, dfw_fileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Dfw_file.
   * @param {dfw_fileUpsertArgs} args - Arguments to update or create a Dfw_file.
   * @example
   * // Update or create a Dfw_file
   * const dfw_file = await prisma.dfw_file.upsert({
   *   create: {
   *     // ... data to create a Dfw_file
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dfw_file we want to update
   *   }
   * })
   */
  upsert<T extends dfw_fileUpsertArgs>(args: Prisma.SelectSubset<T, dfw_fileUpsertArgs<ExtArgs>>): Prisma.Prisma__dfw_fileClient<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Dfw_files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_fileCountArgs} args - Arguments to filter Dfw_files to count.
   * @example
   * // Count the number of Dfw_files
   * const count = await prisma.dfw_file.count({
   *   where: {
   *     // ... the filter for the Dfw_files we want to count
   *   }
   * })
  **/
  count<T extends dfw_fileCountArgs>(
    args?: Prisma.Subset<T, dfw_fileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Dfw_fileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dfw_file.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Dfw_fileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Dfw_fileAggregateArgs>(args: Prisma.Subset<T, Dfw_fileAggregateArgs>): Prisma.PrismaPromise<GetDfw_fileAggregateType<T>>

  /**
   * Group by Dfw_file.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_fileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dfw_fileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dfw_fileGroupByArgs['orderBy'] }
      : { orderBy?: dfw_fileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dfw_fileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDfw_fileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dfw_file model
 */
readonly fields: dfw_fileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dfw_file.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dfw_fileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.dfw_file$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.dfw_file$userArgs<ExtArgs>>): Prisma.Prisma__dfw_userClient<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  parent<T extends Prisma.dfw_file$parentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.dfw_file$parentArgs<ExtArgs>>): Prisma.Prisma__dfw_fileClient<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  children<T extends Prisma.dfw_file$childrenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.dfw_file$childrenArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dfw_file model
 */
export interface dfw_fileFieldRefs {
  readonly id: Prisma.FieldRef<"dfw_file", 'String'>
  readonly name: Prisma.FieldRef<"dfw_file", 'String'>
  readonly path: Prisma.FieldRef<"dfw_file", 'String'>
  readonly url: Prisma.FieldRef<"dfw_file", 'String'>
  readonly variant: Prisma.FieldRef<"dfw_file", 'String'>
  readonly size: Prisma.FieldRef<"dfw_file", 'Int'>
  readonly checksum: Prisma.FieldRef<"dfw_file", 'String'>
  readonly mimetype: Prisma.FieldRef<"dfw_file", 'String'>
  readonly storage: Prisma.FieldRef<"dfw_file", 'DFW_FILE_STORAGE'>
  readonly expire: Prisma.FieldRef<"dfw_file", 'DateTime'>
  readonly metadata: Prisma.FieldRef<"dfw_file", 'Json'>
  readonly idParent: Prisma.FieldRef<"dfw_file", 'String'>
  readonly idUser: Prisma.FieldRef<"dfw_file", 'String'>
  readonly createdAt: Prisma.FieldRef<"dfw_file", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"dfw_file", 'DateTime'>
}
    

// Custom InputTypes
/**
 * dfw_file findUnique
 */
export type dfw_fileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  /**
   * Filter, which dfw_file to fetch.
   */
  where: Prisma.dfw_fileWhereUniqueInput
}

/**
 * dfw_file findUniqueOrThrow
 */
export type dfw_fileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  /**
   * Filter, which dfw_file to fetch.
   */
  where: Prisma.dfw_fileWhereUniqueInput
}

/**
 * dfw_file findFirst
 */
export type dfw_fileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  /**
   * Filter, which dfw_file to fetch.
   */
  where?: Prisma.dfw_fileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_files to fetch.
   */
  orderBy?: Prisma.dfw_fileOrderByWithRelationInput | Prisma.dfw_fileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dfw_files.
   */
  cursor?: Prisma.dfw_fileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dfw_files.
   */
  distinct?: Prisma.Dfw_fileScalarFieldEnum | Prisma.Dfw_fileScalarFieldEnum[]
}

/**
 * dfw_file findFirstOrThrow
 */
export type dfw_fileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  /**
   * Filter, which dfw_file to fetch.
   */
  where?: Prisma.dfw_fileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_files to fetch.
   */
  orderBy?: Prisma.dfw_fileOrderByWithRelationInput | Prisma.dfw_fileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dfw_files.
   */
  cursor?: Prisma.dfw_fileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dfw_files.
   */
  distinct?: Prisma.Dfw_fileScalarFieldEnum | Prisma.Dfw_fileScalarFieldEnum[]
}

/**
 * dfw_file findMany
 */
export type dfw_fileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  /**
   * Filter, which dfw_files to fetch.
   */
  where?: Prisma.dfw_fileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_files to fetch.
   */
  orderBy?: Prisma.dfw_fileOrderByWithRelationInput | Prisma.dfw_fileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dfw_files.
   */
  cursor?: Prisma.dfw_fileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_files.
   */
  skip?: number
  distinct?: Prisma.Dfw_fileScalarFieldEnum | Prisma.Dfw_fileScalarFieldEnum[]
}

/**
 * dfw_file create
 */
export type dfw_fileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  /**
   * The data needed to create a dfw_file.
   */
  data: Prisma.XOR<Prisma.dfw_fileCreateInput, Prisma.dfw_fileUncheckedCreateInput>
}

/**
 * dfw_file createMany
 */
export type dfw_fileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dfw_files.
   */
  data: Prisma.dfw_fileCreateManyInput | Prisma.dfw_fileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dfw_file createManyAndReturn
 */
export type dfw_fileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * The data used to create many dfw_files.
   */
  data: Prisma.dfw_fileCreateManyInput | Prisma.dfw_fileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * dfw_file update
 */
export type dfw_fileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  /**
   * The data needed to update a dfw_file.
   */
  data: Prisma.XOR<Prisma.dfw_fileUpdateInput, Prisma.dfw_fileUncheckedUpdateInput>
  /**
   * Choose, which dfw_file to update.
   */
  where: Prisma.dfw_fileWhereUniqueInput
}

/**
 * dfw_file updateMany
 */
export type dfw_fileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dfw_files.
   */
  data: Prisma.XOR<Prisma.dfw_fileUpdateManyMutationInput, Prisma.dfw_fileUncheckedUpdateManyInput>
  /**
   * Filter which dfw_files to update
   */
  where?: Prisma.dfw_fileWhereInput
  /**
   * Limit how many dfw_files to update.
   */
  limit?: number
}

/**
 * dfw_file updateManyAndReturn
 */
export type dfw_fileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * The data used to update dfw_files.
   */
  data: Prisma.XOR<Prisma.dfw_fileUpdateManyMutationInput, Prisma.dfw_fileUncheckedUpdateManyInput>
  /**
   * Filter which dfw_files to update
   */
  where?: Prisma.dfw_fileWhereInput
  /**
   * Limit how many dfw_files to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * dfw_file upsert
 */
export type dfw_fileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  /**
   * The filter to search for the dfw_file to update in case it exists.
   */
  where: Prisma.dfw_fileWhereUniqueInput
  /**
   * In case the dfw_file found by the `where` argument doesn't exist, create a new dfw_file with this data.
   */
  create: Prisma.XOR<Prisma.dfw_fileCreateInput, Prisma.dfw_fileUncheckedCreateInput>
  /**
   * In case the dfw_file was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dfw_fileUpdateInput, Prisma.dfw_fileUncheckedUpdateInput>
}

/**
 * dfw_file delete
 */
export type dfw_fileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  /**
   * Filter which dfw_file to delete.
   */
  where: Prisma.dfw_fileWhereUniqueInput
}

/**
 * dfw_file deleteMany
 */
export type dfw_fileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dfw_files to delete
   */
  where?: Prisma.dfw_fileWhereInput
  /**
   * Limit how many dfw_files to delete.
   */
  limit?: number
}

/**
 * dfw_file.user
 */
export type dfw_file$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  where?: Prisma.dfw_userWhereInput
}

/**
 * dfw_file.parent
 */
export type dfw_file$parentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  where?: Prisma.dfw_fileWhereInput
}

/**
 * dfw_file.children
 */
export type dfw_file$childrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  where?: Prisma.dfw_fileWhereInput
  orderBy?: Prisma.dfw_fileOrderByWithRelationInput | Prisma.dfw_fileOrderByWithRelationInput[]
  cursor?: Prisma.dfw_fileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Dfw_fileScalarFieldEnum | Prisma.Dfw_fileScalarFieldEnum[]
}

/**
 * dfw_file without action
 */
export type dfw_fileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
}
