
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dfw_credential` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dfw_credential
 * 
 */
export type dfw_credentialModel = runtime.Types.Result.DefaultSelection<Prisma.$dfw_credentialPayload>

export type AggregateDfw_credential = {
  _count: Dfw_credentialCountAggregateOutputType | null
  _min: Dfw_credentialMinAggregateOutputType | null
  _max: Dfw_credentialMaxAggregateOutputType | null
}

export type Dfw_credentialMinAggregateOutputType = {
  name: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Dfw_credentialMaxAggregateOutputType = {
  name: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Dfw_credentialCountAggregateOutputType = {
  name: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type Dfw_credentialMinAggregateInputType = {
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type Dfw_credentialMaxAggregateInputType = {
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type Dfw_credentialCountAggregateInputType = {
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type Dfw_credentialAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dfw_credential to aggregate.
   */
  where?: Prisma.dfw_credentialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_credentials to fetch.
   */
  orderBy?: Prisma.dfw_credentialOrderByWithRelationInput | Prisma.dfw_credentialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dfw_credentialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_credentials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_credentials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dfw_credentials
  **/
  _count?: true | Dfw_credentialCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Dfw_credentialMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Dfw_credentialMaxAggregateInputType
}

export type GetDfw_credentialAggregateType<T extends Dfw_credentialAggregateArgs> = {
      [P in keyof T & keyof AggregateDfw_credential]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDfw_credential[P]>
    : Prisma.GetScalarType<T[P], AggregateDfw_credential[P]>
}




export type dfw_credentialGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_credentialWhereInput
  orderBy?: Prisma.dfw_credentialOrderByWithAggregationInput | Prisma.dfw_credentialOrderByWithAggregationInput[]
  by: Prisma.Dfw_credentialScalarFieldEnum[] | Prisma.Dfw_credentialScalarFieldEnum
  having?: Prisma.dfw_credentialScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Dfw_credentialCountAggregateInputType | true
  _min?: Dfw_credentialMinAggregateInputType
  _max?: Dfw_credentialMaxAggregateInputType
}

export type Dfw_credentialGroupByOutputType = {
  name: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: Dfw_credentialCountAggregateOutputType | null
  _min: Dfw_credentialMinAggregateOutputType | null
  _max: Dfw_credentialMaxAggregateOutputType | null
}

type GetDfw_credentialGroupByPayload<T extends dfw_credentialGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Dfw_credentialGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Dfw_credentialGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Dfw_credentialGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Dfw_credentialGroupByOutputType[P]>
      }
    >
  >



export type dfw_credentialWhereInput = {
  AND?: Prisma.dfw_credentialWhereInput | Prisma.dfw_credentialWhereInput[]
  OR?: Prisma.dfw_credentialWhereInput[]
  NOT?: Prisma.dfw_credentialWhereInput | Prisma.dfw_credentialWhereInput[]
  name?: Prisma.StringFilter<"dfw_credential"> | string
  description?: Prisma.StringNullableFilter<"dfw_credential"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_credential"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_credential"> | Date | string
  users?: Prisma.Dfw_userListRelationFilter
  access?: Prisma.Dfw_accessListRelationFilter
}

export type dfw_credentialOrderByWithRelationInput = {
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  users?: Prisma.dfw_userOrderByRelationAggregateInput
  access?: Prisma.dfw_accessOrderByRelationAggregateInput
}

export type dfw_credentialWhereUniqueInput = Prisma.AtLeast<{
  name?: string
  AND?: Prisma.dfw_credentialWhereInput | Prisma.dfw_credentialWhereInput[]
  OR?: Prisma.dfw_credentialWhereInput[]
  NOT?: Prisma.dfw_credentialWhereInput | Prisma.dfw_credentialWhereInput[]
  description?: Prisma.StringNullableFilter<"dfw_credential"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_credential"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_credential"> | Date | string
  users?: Prisma.Dfw_userListRelationFilter
  access?: Prisma.Dfw_accessListRelationFilter
}, "name">

export type dfw_credentialOrderByWithAggregationInput = {
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.dfw_credentialCountOrderByAggregateInput
  _max?: Prisma.dfw_credentialMaxOrderByAggregateInput
  _min?: Prisma.dfw_credentialMinOrderByAggregateInput
}

export type dfw_credentialScalarWhereWithAggregatesInput = {
  AND?: Prisma.dfw_credentialScalarWhereWithAggregatesInput | Prisma.dfw_credentialScalarWhereWithAggregatesInput[]
  OR?: Prisma.dfw_credentialScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dfw_credentialScalarWhereWithAggregatesInput | Prisma.dfw_credentialScalarWhereWithAggregatesInput[]
  name?: Prisma.StringWithAggregatesFilter<"dfw_credential"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"dfw_credential"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"dfw_credential"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"dfw_credential"> | Date | string
}

export type dfw_credentialCreateInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.dfw_userCreateNestedManyWithoutCredentialsInput
  access?: Prisma.dfw_accessCreateNestedManyWithoutCredentialsInput
}

export type dfw_credentialUncheckedCreateInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.dfw_userUncheckedCreateNestedManyWithoutCredentialsInput
  access?: Prisma.dfw_accessUncheckedCreateNestedManyWithoutCredentialsInput
}

export type dfw_credentialUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.dfw_userUpdateManyWithoutCredentialsNestedInput
  access?: Prisma.dfw_accessUpdateManyWithoutCredentialsNestedInput
}

export type dfw_credentialUncheckedUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.dfw_userUncheckedUpdateManyWithoutCredentialsNestedInput
  access?: Prisma.dfw_accessUncheckedUpdateManyWithoutCredentialsNestedInput
}

export type dfw_credentialCreateManyInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type dfw_credentialUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_credentialUncheckedUpdateManyInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Dfw_credentialListRelationFilter = {
  every?: Prisma.dfw_credentialWhereInput
  some?: Prisma.dfw_credentialWhereInput
  none?: Prisma.dfw_credentialWhereInput
}

export type dfw_credentialOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type dfw_credentialCountOrderByAggregateInput = {
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type dfw_credentialMaxOrderByAggregateInput = {
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type dfw_credentialMinOrderByAggregateInput = {
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type dfw_credentialCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.dfw_credentialCreateWithoutUsersInput, Prisma.dfw_credentialUncheckedCreateWithoutUsersInput> | Prisma.dfw_credentialCreateWithoutUsersInput[] | Prisma.dfw_credentialUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.dfw_credentialCreateOrConnectWithoutUsersInput | Prisma.dfw_credentialCreateOrConnectWithoutUsersInput[]
  connect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
}

export type dfw_credentialUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.dfw_credentialCreateWithoutUsersInput, Prisma.dfw_credentialUncheckedCreateWithoutUsersInput> | Prisma.dfw_credentialCreateWithoutUsersInput[] | Prisma.dfw_credentialUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.dfw_credentialCreateOrConnectWithoutUsersInput | Prisma.dfw_credentialCreateOrConnectWithoutUsersInput[]
  connect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
}

export type dfw_credentialUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_credentialCreateWithoutUsersInput, Prisma.dfw_credentialUncheckedCreateWithoutUsersInput> | Prisma.dfw_credentialCreateWithoutUsersInput[] | Prisma.dfw_credentialUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.dfw_credentialCreateOrConnectWithoutUsersInput | Prisma.dfw_credentialCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.dfw_credentialUpsertWithWhereUniqueWithoutUsersInput | Prisma.dfw_credentialUpsertWithWhereUniqueWithoutUsersInput[]
  set?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  disconnect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  delete?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  connect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  update?: Prisma.dfw_credentialUpdateWithWhereUniqueWithoutUsersInput | Prisma.dfw_credentialUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.dfw_credentialUpdateManyWithWhereWithoutUsersInput | Prisma.dfw_credentialUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.dfw_credentialScalarWhereInput | Prisma.dfw_credentialScalarWhereInput[]
}

export type dfw_credentialUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_credentialCreateWithoutUsersInput, Prisma.dfw_credentialUncheckedCreateWithoutUsersInput> | Prisma.dfw_credentialCreateWithoutUsersInput[] | Prisma.dfw_credentialUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.dfw_credentialCreateOrConnectWithoutUsersInput | Prisma.dfw_credentialCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.dfw_credentialUpsertWithWhereUniqueWithoutUsersInput | Prisma.dfw_credentialUpsertWithWhereUniqueWithoutUsersInput[]
  set?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  disconnect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  delete?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  connect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  update?: Prisma.dfw_credentialUpdateWithWhereUniqueWithoutUsersInput | Prisma.dfw_credentialUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.dfw_credentialUpdateManyWithWhereWithoutUsersInput | Prisma.dfw_credentialUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.dfw_credentialScalarWhereInput | Prisma.dfw_credentialScalarWhereInput[]
}

export type dfw_credentialCreateNestedManyWithoutAccessInput = {
  create?: Prisma.XOR<Prisma.dfw_credentialCreateWithoutAccessInput, Prisma.dfw_credentialUncheckedCreateWithoutAccessInput> | Prisma.dfw_credentialCreateWithoutAccessInput[] | Prisma.dfw_credentialUncheckedCreateWithoutAccessInput[]
  connectOrCreate?: Prisma.dfw_credentialCreateOrConnectWithoutAccessInput | Prisma.dfw_credentialCreateOrConnectWithoutAccessInput[]
  connect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
}

export type dfw_credentialUncheckedCreateNestedManyWithoutAccessInput = {
  create?: Prisma.XOR<Prisma.dfw_credentialCreateWithoutAccessInput, Prisma.dfw_credentialUncheckedCreateWithoutAccessInput> | Prisma.dfw_credentialCreateWithoutAccessInput[] | Prisma.dfw_credentialUncheckedCreateWithoutAccessInput[]
  connectOrCreate?: Prisma.dfw_credentialCreateOrConnectWithoutAccessInput | Prisma.dfw_credentialCreateOrConnectWithoutAccessInput[]
  connect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
}

export type dfw_credentialUpdateManyWithoutAccessNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_credentialCreateWithoutAccessInput, Prisma.dfw_credentialUncheckedCreateWithoutAccessInput> | Prisma.dfw_credentialCreateWithoutAccessInput[] | Prisma.dfw_credentialUncheckedCreateWithoutAccessInput[]
  connectOrCreate?: Prisma.dfw_credentialCreateOrConnectWithoutAccessInput | Prisma.dfw_credentialCreateOrConnectWithoutAccessInput[]
  upsert?: Prisma.dfw_credentialUpsertWithWhereUniqueWithoutAccessInput | Prisma.dfw_credentialUpsertWithWhereUniqueWithoutAccessInput[]
  set?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  disconnect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  delete?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  connect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  update?: Prisma.dfw_credentialUpdateWithWhereUniqueWithoutAccessInput | Prisma.dfw_credentialUpdateWithWhereUniqueWithoutAccessInput[]
  updateMany?: Prisma.dfw_credentialUpdateManyWithWhereWithoutAccessInput | Prisma.dfw_credentialUpdateManyWithWhereWithoutAccessInput[]
  deleteMany?: Prisma.dfw_credentialScalarWhereInput | Prisma.dfw_credentialScalarWhereInput[]
}

export type dfw_credentialUncheckedUpdateManyWithoutAccessNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_credentialCreateWithoutAccessInput, Prisma.dfw_credentialUncheckedCreateWithoutAccessInput> | Prisma.dfw_credentialCreateWithoutAccessInput[] | Prisma.dfw_credentialUncheckedCreateWithoutAccessInput[]
  connectOrCreate?: Prisma.dfw_credentialCreateOrConnectWithoutAccessInput | Prisma.dfw_credentialCreateOrConnectWithoutAccessInput[]
  upsert?: Prisma.dfw_credentialUpsertWithWhereUniqueWithoutAccessInput | Prisma.dfw_credentialUpsertWithWhereUniqueWithoutAccessInput[]
  set?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  disconnect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  delete?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  connect?: Prisma.dfw_credentialWhereUniqueInput | Prisma.dfw_credentialWhereUniqueInput[]
  update?: Prisma.dfw_credentialUpdateWithWhereUniqueWithoutAccessInput | Prisma.dfw_credentialUpdateWithWhereUniqueWithoutAccessInput[]
  updateMany?: Prisma.dfw_credentialUpdateManyWithWhereWithoutAccessInput | Prisma.dfw_credentialUpdateManyWithWhereWithoutAccessInput[]
  deleteMany?: Prisma.dfw_credentialScalarWhereInput | Prisma.dfw_credentialScalarWhereInput[]
}

export type dfw_credentialCreateWithoutUsersInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  access?: Prisma.dfw_accessCreateNestedManyWithoutCredentialsInput
}

export type dfw_credentialUncheckedCreateWithoutUsersInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  access?: Prisma.dfw_accessUncheckedCreateNestedManyWithoutCredentialsInput
}

export type dfw_credentialCreateOrConnectWithoutUsersInput = {
  where: Prisma.dfw_credentialWhereUniqueInput
  create: Prisma.XOR<Prisma.dfw_credentialCreateWithoutUsersInput, Prisma.dfw_credentialUncheckedCreateWithoutUsersInput>
}

export type dfw_credentialUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.dfw_credentialWhereUniqueInput
  update: Prisma.XOR<Prisma.dfw_credentialUpdateWithoutUsersInput, Prisma.dfw_credentialUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.dfw_credentialCreateWithoutUsersInput, Prisma.dfw_credentialUncheckedCreateWithoutUsersInput>
}

export type dfw_credentialUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.dfw_credentialWhereUniqueInput
  data: Prisma.XOR<Prisma.dfw_credentialUpdateWithoutUsersInput, Prisma.dfw_credentialUncheckedUpdateWithoutUsersInput>
}

export type dfw_credentialUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.dfw_credentialScalarWhereInput
  data: Prisma.XOR<Prisma.dfw_credentialUpdateManyMutationInput, Prisma.dfw_credentialUncheckedUpdateManyWithoutUsersInput>
}

export type dfw_credentialScalarWhereInput = {
  AND?: Prisma.dfw_credentialScalarWhereInput | Prisma.dfw_credentialScalarWhereInput[]
  OR?: Prisma.dfw_credentialScalarWhereInput[]
  NOT?: Prisma.dfw_credentialScalarWhereInput | Prisma.dfw_credentialScalarWhereInput[]
  name?: Prisma.StringFilter<"dfw_credential"> | string
  description?: Prisma.StringNullableFilter<"dfw_credential"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_credential"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_credential"> | Date | string
}

export type dfw_credentialCreateWithoutAccessInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.dfw_userCreateNestedManyWithoutCredentialsInput
}

export type dfw_credentialUncheckedCreateWithoutAccessInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.dfw_userUncheckedCreateNestedManyWithoutCredentialsInput
}

export type dfw_credentialCreateOrConnectWithoutAccessInput = {
  where: Prisma.dfw_credentialWhereUniqueInput
  create: Prisma.XOR<Prisma.dfw_credentialCreateWithoutAccessInput, Prisma.dfw_credentialUncheckedCreateWithoutAccessInput>
}

export type dfw_credentialUpsertWithWhereUniqueWithoutAccessInput = {
  where: Prisma.dfw_credentialWhereUniqueInput
  update: Prisma.XOR<Prisma.dfw_credentialUpdateWithoutAccessInput, Prisma.dfw_credentialUncheckedUpdateWithoutAccessInput>
  create: Prisma.XOR<Prisma.dfw_credentialCreateWithoutAccessInput, Prisma.dfw_credentialUncheckedCreateWithoutAccessInput>
}

export type dfw_credentialUpdateWithWhereUniqueWithoutAccessInput = {
  where: Prisma.dfw_credentialWhereUniqueInput
  data: Prisma.XOR<Prisma.dfw_credentialUpdateWithoutAccessInput, Prisma.dfw_credentialUncheckedUpdateWithoutAccessInput>
}

export type dfw_credentialUpdateManyWithWhereWithoutAccessInput = {
  where: Prisma.dfw_credentialScalarWhereInput
  data: Prisma.XOR<Prisma.dfw_credentialUpdateManyMutationInput, Prisma.dfw_credentialUncheckedUpdateManyWithoutAccessInput>
}

export type dfw_credentialUpdateWithoutUsersInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  access?: Prisma.dfw_accessUpdateManyWithoutCredentialsNestedInput
}

export type dfw_credentialUncheckedUpdateWithoutUsersInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  access?: Prisma.dfw_accessUncheckedUpdateManyWithoutCredentialsNestedInput
}

export type dfw_credentialUncheckedUpdateManyWithoutUsersInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_credentialUpdateWithoutAccessInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.dfw_userUpdateManyWithoutCredentialsNestedInput
}

export type dfw_credentialUncheckedUpdateWithoutAccessInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.dfw_userUncheckedUpdateManyWithoutCredentialsNestedInput
}

export type dfw_credentialUncheckedUpdateManyWithoutAccessInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type Dfw_credentialCountOutputType
 */

export type Dfw_credentialCountOutputType = {
  users: number
  access: number
}

export type Dfw_credentialCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Dfw_credentialCountOutputTypeCountUsersArgs
  access?: boolean | Dfw_credentialCountOutputTypeCountAccessArgs
}

/**
 * Dfw_credentialCountOutputType without action
 */
export type Dfw_credentialCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dfw_credentialCountOutputType
   */
  select?: Prisma.Dfw_credentialCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Dfw_credentialCountOutputType without action
 */
export type Dfw_credentialCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_userWhereInput
}

/**
 * Dfw_credentialCountOutputType without action
 */
export type Dfw_credentialCountOutputTypeCountAccessArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_accessWhereInput
}


export type dfw_credentialSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  users?: boolean | Prisma.dfw_credential$usersArgs<ExtArgs>
  access?: boolean | Prisma.dfw_credential$accessArgs<ExtArgs>
  _count?: boolean | Prisma.Dfw_credentialCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dfw_credential"]>

export type dfw_credentialSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dfw_credential"]>

export type dfw_credentialSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dfw_credential"]>

export type dfw_credentialSelectScalar = {
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type dfw_credentialOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["dfw_credential"]>
export type dfw_credentialInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.dfw_credential$usersArgs<ExtArgs>
  access?: boolean | Prisma.dfw_credential$accessArgs<ExtArgs>
  _count?: boolean | Prisma.Dfw_credentialCountOutputTypeDefaultArgs<ExtArgs>
}
export type dfw_credentialIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type dfw_credentialIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $dfw_credentialPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dfw_credential"
  objects: {
    users: Prisma.$dfw_userPayload<ExtArgs>[]
    access: Prisma.$dfw_accessPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    name: string
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dfw_credential"]>
  composites: {}
}

export type dfw_credentialGetPayload<S extends boolean | null | undefined | dfw_credentialDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload, S>

export type dfw_credentialCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dfw_credentialFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Dfw_credentialCountAggregateInputType | true
  }

export interface dfw_credentialDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dfw_credential'], meta: { name: 'dfw_credential' } }
  /**
   * Find zero or one Dfw_credential that matches the filter.
   * @param {dfw_credentialFindUniqueArgs} args - Arguments to find a Dfw_credential
   * @example
   * // Get one Dfw_credential
   * const dfw_credential = await prisma.dfw_credential.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dfw_credentialFindUniqueArgs>(args: Prisma.SelectSubset<T, dfw_credentialFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dfw_credentialClient<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dfw_credential that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dfw_credentialFindUniqueOrThrowArgs} args - Arguments to find a Dfw_credential
   * @example
   * // Get one Dfw_credential
   * const dfw_credential = await prisma.dfw_credential.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dfw_credentialFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dfw_credentialFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dfw_credentialClient<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dfw_credential that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_credentialFindFirstArgs} args - Arguments to find a Dfw_credential
   * @example
   * // Get one Dfw_credential
   * const dfw_credential = await prisma.dfw_credential.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dfw_credentialFindFirstArgs>(args?: Prisma.SelectSubset<T, dfw_credentialFindFirstArgs<ExtArgs>>): Prisma.Prisma__dfw_credentialClient<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dfw_credential that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_credentialFindFirstOrThrowArgs} args - Arguments to find a Dfw_credential
   * @example
   * // Get one Dfw_credential
   * const dfw_credential = await prisma.dfw_credential.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dfw_credentialFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dfw_credentialFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dfw_credentialClient<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Dfw_credentials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_credentialFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Dfw_credentials
   * const dfw_credentials = await prisma.dfw_credential.findMany()
   * 
   * // Get first 10 Dfw_credentials
   * const dfw_credentials = await prisma.dfw_credential.findMany({ take: 10 })
   * 
   * // Only select the `name`
   * const dfw_credentialWithNameOnly = await prisma.dfw_credential.findMany({ select: { name: true } })
   * 
   */
  findMany<T extends dfw_credentialFindManyArgs>(args?: Prisma.SelectSubset<T, dfw_credentialFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dfw_credential.
   * @param {dfw_credentialCreateArgs} args - Arguments to create a Dfw_credential.
   * @example
   * // Create one Dfw_credential
   * const Dfw_credential = await prisma.dfw_credential.create({
   *   data: {
   *     // ... data to create a Dfw_credential
   *   }
   * })
   * 
   */
  create<T extends dfw_credentialCreateArgs>(args: Prisma.SelectSubset<T, dfw_credentialCreateArgs<ExtArgs>>): Prisma.Prisma__dfw_credentialClient<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Dfw_credentials.
   * @param {dfw_credentialCreateManyArgs} args - Arguments to create many Dfw_credentials.
   * @example
   * // Create many Dfw_credentials
   * const dfw_credential = await prisma.dfw_credential.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dfw_credentialCreateManyArgs>(args?: Prisma.SelectSubset<T, dfw_credentialCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Dfw_credentials and returns the data saved in the database.
   * @param {dfw_credentialCreateManyAndReturnArgs} args - Arguments to create many Dfw_credentials.
   * @example
   * // Create many Dfw_credentials
   * const dfw_credential = await prisma.dfw_credential.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Dfw_credentials and only return the `name`
   * const dfw_credentialWithNameOnly = await prisma.dfw_credential.createManyAndReturn({
   *   select: { name: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends dfw_credentialCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, dfw_credentialCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Dfw_credential.
   * @param {dfw_credentialDeleteArgs} args - Arguments to delete one Dfw_credential.
   * @example
   * // Delete one Dfw_credential
   * const Dfw_credential = await prisma.dfw_credential.delete({
   *   where: {
   *     // ... filter to delete one Dfw_credential
   *   }
   * })
   * 
   */
  delete<T extends dfw_credentialDeleteArgs>(args: Prisma.SelectSubset<T, dfw_credentialDeleteArgs<ExtArgs>>): Prisma.Prisma__dfw_credentialClient<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dfw_credential.
   * @param {dfw_credentialUpdateArgs} args - Arguments to update one Dfw_credential.
   * @example
   * // Update one Dfw_credential
   * const dfw_credential = await prisma.dfw_credential.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dfw_credentialUpdateArgs>(args: Prisma.SelectSubset<T, dfw_credentialUpdateArgs<ExtArgs>>): Prisma.Prisma__dfw_credentialClient<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Dfw_credentials.
   * @param {dfw_credentialDeleteManyArgs} args - Arguments to filter Dfw_credentials to delete.
   * @example
   * // Delete a few Dfw_credentials
   * const { count } = await prisma.dfw_credential.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dfw_credentialDeleteManyArgs>(args?: Prisma.SelectSubset<T, dfw_credentialDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dfw_credentials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_credentialUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Dfw_credentials
   * const dfw_credential = await prisma.dfw_credential.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dfw_credentialUpdateManyArgs>(args: Prisma.SelectSubset<T, dfw_credentialUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dfw_credentials and returns the data updated in the database.
   * @param {dfw_credentialUpdateManyAndReturnArgs} args - Arguments to update many Dfw_credentials.
   * @example
   * // Update many Dfw_credentials
   * const dfw_credential = await prisma.dfw_credential.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Dfw_credentials and only return the `name`
   * const dfw_credentialWithNameOnly = await prisma.dfw_credential.updateManyAndReturn({
   *   select: { name: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends dfw_credentialUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, dfw_credentialUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Dfw_credential.
   * @param {dfw_credentialUpsertArgs} args - Arguments to update or create a Dfw_credential.
   * @example
   * // Update or create a Dfw_credential
   * const dfw_credential = await prisma.dfw_credential.upsert({
   *   create: {
   *     // ... data to create a Dfw_credential
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dfw_credential we want to update
   *   }
   * })
   */
  upsert<T extends dfw_credentialUpsertArgs>(args: Prisma.SelectSubset<T, dfw_credentialUpsertArgs<ExtArgs>>): Prisma.Prisma__dfw_credentialClient<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Dfw_credentials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_credentialCountArgs} args - Arguments to filter Dfw_credentials to count.
   * @example
   * // Count the number of Dfw_credentials
   * const count = await prisma.dfw_credential.count({
   *   where: {
   *     // ... the filter for the Dfw_credentials we want to count
   *   }
   * })
  **/
  count<T extends dfw_credentialCountArgs>(
    args?: Prisma.Subset<T, dfw_credentialCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Dfw_credentialCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dfw_credential.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Dfw_credentialAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Dfw_credentialAggregateArgs>(args: Prisma.Subset<T, Dfw_credentialAggregateArgs>): Prisma.PrismaPromise<GetDfw_credentialAggregateType<T>>

  /**
   * Group by Dfw_credential.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_credentialGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dfw_credentialGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dfw_credentialGroupByArgs['orderBy'] }
      : { orderBy?: dfw_credentialGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dfw_credentialGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDfw_credentialGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dfw_credential model
 */
readonly fields: dfw_credentialFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dfw_credential.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dfw_credentialClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.dfw_credential$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.dfw_credential$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  access<T extends Prisma.dfw_credential$accessArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.dfw_credential$accessArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dfw_credential model
 */
export interface dfw_credentialFieldRefs {
  readonly name: Prisma.FieldRef<"dfw_credential", 'String'>
  readonly description: Prisma.FieldRef<"dfw_credential", 'String'>
  readonly createdAt: Prisma.FieldRef<"dfw_credential", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"dfw_credential", 'DateTime'>
}
    

// Custom InputTypes
/**
 * dfw_credential findUnique
 */
export type dfw_credentialFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  /**
   * Filter, which dfw_credential to fetch.
   */
  where: Prisma.dfw_credentialWhereUniqueInput
}

/**
 * dfw_credential findUniqueOrThrow
 */
export type dfw_credentialFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  /**
   * Filter, which dfw_credential to fetch.
   */
  where: Prisma.dfw_credentialWhereUniqueInput
}

/**
 * dfw_credential findFirst
 */
export type dfw_credentialFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  /**
   * Filter, which dfw_credential to fetch.
   */
  where?: Prisma.dfw_credentialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_credentials to fetch.
   */
  orderBy?: Prisma.dfw_credentialOrderByWithRelationInput | Prisma.dfw_credentialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dfw_credentials.
   */
  cursor?: Prisma.dfw_credentialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_credentials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_credentials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dfw_credentials.
   */
  distinct?: Prisma.Dfw_credentialScalarFieldEnum | Prisma.Dfw_credentialScalarFieldEnum[]
}

/**
 * dfw_credential findFirstOrThrow
 */
export type dfw_credentialFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  /**
   * Filter, which dfw_credential to fetch.
   */
  where?: Prisma.dfw_credentialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_credentials to fetch.
   */
  orderBy?: Prisma.dfw_credentialOrderByWithRelationInput | Prisma.dfw_credentialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dfw_credentials.
   */
  cursor?: Prisma.dfw_credentialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_credentials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_credentials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dfw_credentials.
   */
  distinct?: Prisma.Dfw_credentialScalarFieldEnum | Prisma.Dfw_credentialScalarFieldEnum[]
}

/**
 * dfw_credential findMany
 */
export type dfw_credentialFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  /**
   * Filter, which dfw_credentials to fetch.
   */
  where?: Prisma.dfw_credentialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_credentials to fetch.
   */
  orderBy?: Prisma.dfw_credentialOrderByWithRelationInput | Prisma.dfw_credentialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dfw_credentials.
   */
  cursor?: Prisma.dfw_credentialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_credentials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_credentials.
   */
  skip?: number
  distinct?: Prisma.Dfw_credentialScalarFieldEnum | Prisma.Dfw_credentialScalarFieldEnum[]
}

/**
 * dfw_credential create
 */
export type dfw_credentialCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  /**
   * The data needed to create a dfw_credential.
   */
  data: Prisma.XOR<Prisma.dfw_credentialCreateInput, Prisma.dfw_credentialUncheckedCreateInput>
}

/**
 * dfw_credential createMany
 */
export type dfw_credentialCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dfw_credentials.
   */
  data: Prisma.dfw_credentialCreateManyInput | Prisma.dfw_credentialCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dfw_credential createManyAndReturn
 */
export type dfw_credentialCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * The data used to create many dfw_credentials.
   */
  data: Prisma.dfw_credentialCreateManyInput | Prisma.dfw_credentialCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dfw_credential update
 */
export type dfw_credentialUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  /**
   * The data needed to update a dfw_credential.
   */
  data: Prisma.XOR<Prisma.dfw_credentialUpdateInput, Prisma.dfw_credentialUncheckedUpdateInput>
  /**
   * Choose, which dfw_credential to update.
   */
  where: Prisma.dfw_credentialWhereUniqueInput
}

/**
 * dfw_credential updateMany
 */
export type dfw_credentialUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dfw_credentials.
   */
  data: Prisma.XOR<Prisma.dfw_credentialUpdateManyMutationInput, Prisma.dfw_credentialUncheckedUpdateManyInput>
  /**
   * Filter which dfw_credentials to update
   */
  where?: Prisma.dfw_credentialWhereInput
  /**
   * Limit how many dfw_credentials to update.
   */
  limit?: number
}

/**
 * dfw_credential updateManyAndReturn
 */
export type dfw_credentialUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * The data used to update dfw_credentials.
   */
  data: Prisma.XOR<Prisma.dfw_credentialUpdateManyMutationInput, Prisma.dfw_credentialUncheckedUpdateManyInput>
  /**
   * Filter which dfw_credentials to update
   */
  where?: Prisma.dfw_credentialWhereInput
  /**
   * Limit how many dfw_credentials to update.
   */
  limit?: number
}

/**
 * dfw_credential upsert
 */
export type dfw_credentialUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  /**
   * The filter to search for the dfw_credential to update in case it exists.
   */
  where: Prisma.dfw_credentialWhereUniqueInput
  /**
   * In case the dfw_credential found by the `where` argument doesn't exist, create a new dfw_credential with this data.
   */
  create: Prisma.XOR<Prisma.dfw_credentialCreateInput, Prisma.dfw_credentialUncheckedCreateInput>
  /**
   * In case the dfw_credential was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dfw_credentialUpdateInput, Prisma.dfw_credentialUncheckedUpdateInput>
}

/**
 * dfw_credential delete
 */
export type dfw_credentialDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  /**
   * Filter which dfw_credential to delete.
   */
  where: Prisma.dfw_credentialWhereUniqueInput
}

/**
 * dfw_credential deleteMany
 */
export type dfw_credentialDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dfw_credentials to delete
   */
  where?: Prisma.dfw_credentialWhereInput
  /**
   * Limit how many dfw_credentials to delete.
   */
  limit?: number
}

/**
 * dfw_credential.users
 */
export type dfw_credential$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  where?: Prisma.dfw_userWhereInput
  orderBy?: Prisma.dfw_userOrderByWithRelationInput | Prisma.dfw_userOrderByWithRelationInput[]
  cursor?: Prisma.dfw_userWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Dfw_userScalarFieldEnum | Prisma.Dfw_userScalarFieldEnum[]
}

/**
 * dfw_credential.access
 */
export type dfw_credential$accessArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
  where?: Prisma.dfw_accessWhereInput
  orderBy?: Prisma.dfw_accessOrderByWithRelationInput | Prisma.dfw_accessOrderByWithRelationInput[]
  cursor?: Prisma.dfw_accessWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Dfw_accessScalarFieldEnum | Prisma.Dfw_accessScalarFieldEnum[]
}

/**
 * dfw_credential without action
 */
export type dfw_credentialDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
}
