
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dfw_access` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dfw_access
 * 
 */
export type dfw_accessModel = runtime.Types.Result.DefaultSelection<Prisma.$dfw_accessPayload>

export type AggregateDfw_access = {
  _count: Dfw_accessCountAggregateOutputType | null
  _min: Dfw_accessMinAggregateOutputType | null
  _max: Dfw_accessMaxAggregateOutputType | null
}

export type Dfw_accessMinAggregateOutputType = {
  name: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Dfw_accessMaxAggregateOutputType = {
  name: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Dfw_accessCountAggregateOutputType = {
  name: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type Dfw_accessMinAggregateInputType = {
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type Dfw_accessMaxAggregateInputType = {
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type Dfw_accessCountAggregateInputType = {
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type Dfw_accessAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dfw_access to aggregate.
   */
  where?: Prisma.dfw_accessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_accesses to fetch.
   */
  orderBy?: Prisma.dfw_accessOrderByWithRelationInput | Prisma.dfw_accessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dfw_accessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_accesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_accesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dfw_accesses
  **/
  _count?: true | Dfw_accessCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Dfw_accessMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Dfw_accessMaxAggregateInputType
}

export type GetDfw_accessAggregateType<T extends Dfw_accessAggregateArgs> = {
      [P in keyof T & keyof AggregateDfw_access]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDfw_access[P]>
    : Prisma.GetScalarType<T[P], AggregateDfw_access[P]>
}




export type dfw_accessGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_accessWhereInput
  orderBy?: Prisma.dfw_accessOrderByWithAggregationInput | Prisma.dfw_accessOrderByWithAggregationInput[]
  by: Prisma.Dfw_accessScalarFieldEnum[] | Prisma.Dfw_accessScalarFieldEnum
  having?: Prisma.dfw_accessScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Dfw_accessCountAggregateInputType | true
  _min?: Dfw_accessMinAggregateInputType
  _max?: Dfw_accessMaxAggregateInputType
}

export type Dfw_accessGroupByOutputType = {
  name: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: Dfw_accessCountAggregateOutputType | null
  _min: Dfw_accessMinAggregateOutputType | null
  _max: Dfw_accessMaxAggregateOutputType | null
}

type GetDfw_accessGroupByPayload<T extends dfw_accessGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Dfw_accessGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Dfw_accessGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Dfw_accessGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Dfw_accessGroupByOutputType[P]>
      }
    >
  >



export type dfw_accessWhereInput = {
  AND?: Prisma.dfw_accessWhereInput | Prisma.dfw_accessWhereInput[]
  OR?: Prisma.dfw_accessWhereInput[]
  NOT?: Prisma.dfw_accessWhereInput | Prisma.dfw_accessWhereInput[]
  name?: Prisma.StringFilter<"dfw_access"> | string
  description?: Prisma.StringNullableFilter<"dfw_access"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_access"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_access"> | Date | string
  credentials?: Prisma.Dfw_credentialListRelationFilter
}

export type dfw_accessOrderByWithRelationInput = {
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  credentials?: Prisma.dfw_credentialOrderByRelationAggregateInput
}

export type dfw_accessWhereUniqueInput = Prisma.AtLeast<{
  name?: string
  AND?: Prisma.dfw_accessWhereInput | Prisma.dfw_accessWhereInput[]
  OR?: Prisma.dfw_accessWhereInput[]
  NOT?: Prisma.dfw_accessWhereInput | Prisma.dfw_accessWhereInput[]
  description?: Prisma.StringNullableFilter<"dfw_access"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_access"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_access"> | Date | string
  credentials?: Prisma.Dfw_credentialListRelationFilter
}, "name">

export type dfw_accessOrderByWithAggregationInput = {
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.dfw_accessCountOrderByAggregateInput
  _max?: Prisma.dfw_accessMaxOrderByAggregateInput
  _min?: Prisma.dfw_accessMinOrderByAggregateInput
}

export type dfw_accessScalarWhereWithAggregatesInput = {
  AND?: Prisma.dfw_accessScalarWhereWithAggregatesInput | Prisma.dfw_accessScalarWhereWithAggregatesInput[]
  OR?: Prisma.dfw_accessScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dfw_accessScalarWhereWithAggregatesInput | Prisma.dfw_accessScalarWhereWithAggregatesInput[]
  name?: Prisma.StringWithAggregatesFilter<"dfw_access"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"dfw_access"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"dfw_access"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"dfw_access"> | Date | string
}

export type dfw_accessCreateInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  credentials?: Prisma.dfw_credentialCreateNestedManyWithoutAccessInput
}

export type dfw_accessUncheckedCreateInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  credentials?: Prisma.dfw_credentialUncheckedCreateNestedManyWithoutAccessInput
}

export type dfw_accessUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  credentials?: Prisma.dfw_credentialUpdateManyWithoutAccessNestedInput
}

export type dfw_accessUncheckedUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  credentials?: Prisma.dfw_credentialUncheckedUpdateManyWithoutAccessNestedInput
}

export type dfw_accessCreateManyInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type dfw_accessUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_accessUncheckedUpdateManyInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_accessCountOrderByAggregateInput = {
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type dfw_accessMaxOrderByAggregateInput = {
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type dfw_accessMinOrderByAggregateInput = {
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type Dfw_accessListRelationFilter = {
  every?: Prisma.dfw_accessWhereInput
  some?: Prisma.dfw_accessWhereInput
  none?: Prisma.dfw_accessWhereInput
}

export type dfw_accessOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type dfw_accessCreateNestedManyWithoutCredentialsInput = {
  create?: Prisma.XOR<Prisma.dfw_accessCreateWithoutCredentialsInput, Prisma.dfw_accessUncheckedCreateWithoutCredentialsInput> | Prisma.dfw_accessCreateWithoutCredentialsInput[] | Prisma.dfw_accessUncheckedCreateWithoutCredentialsInput[]
  connectOrCreate?: Prisma.dfw_accessCreateOrConnectWithoutCredentialsInput | Prisma.dfw_accessCreateOrConnectWithoutCredentialsInput[]
  connect?: Prisma.dfw_accessWhereUniqueInput | Prisma.dfw_accessWhereUniqueInput[]
}

export type dfw_accessUncheckedCreateNestedManyWithoutCredentialsInput = {
  create?: Prisma.XOR<Prisma.dfw_accessCreateWithoutCredentialsInput, Prisma.dfw_accessUncheckedCreateWithoutCredentialsInput> | Prisma.dfw_accessCreateWithoutCredentialsInput[] | Prisma.dfw_accessUncheckedCreateWithoutCredentialsInput[]
  connectOrCreate?: Prisma.dfw_accessCreateOrConnectWithoutCredentialsInput | Prisma.dfw_accessCreateOrConnectWithoutCredentialsInput[]
  connect?: Prisma.dfw_accessWhereUniqueInput | Prisma.dfw_accessWhereUniqueInput[]
}

export type dfw_accessUpdateManyWithoutCredentialsNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_accessCreateWithoutCredentialsInput, Prisma.dfw_accessUncheckedCreateWithoutCredentialsInput> | Prisma.dfw_accessCreateWithoutCredentialsInput[] | Prisma.dfw_accessUncheckedCreateWithoutCredentialsInput[]
  connectOrCreate?: Prisma.dfw_accessCreateOrConnectWithoutCredentialsInput | Prisma.dfw_accessCreateOrConnectWithoutCredentialsInput[]
  upsert?: Prisma.dfw_accessUpsertWithWhereUniqueWithoutCredentialsInput | Prisma.dfw_accessUpsertWithWhereUniqueWithoutCredentialsInput[]
  set?: Prisma.dfw_accessWhereUniqueInput | Prisma.dfw_accessWhereUniqueInput[]
  disconnect?: Prisma.dfw_accessWhereUniqueInput | Prisma.dfw_accessWhereUniqueInput[]
  delete?: Prisma.dfw_accessWhereUniqueInput | Prisma.dfw_accessWhereUniqueInput[]
  connect?: Prisma.dfw_accessWhereUniqueInput | Prisma.dfw_accessWhereUniqueInput[]
  update?: Prisma.dfw_accessUpdateWithWhereUniqueWithoutCredentialsInput | Prisma.dfw_accessUpdateWithWhereUniqueWithoutCredentialsInput[]
  updateMany?: Prisma.dfw_accessUpdateManyWithWhereWithoutCredentialsInput | Prisma.dfw_accessUpdateManyWithWhereWithoutCredentialsInput[]
  deleteMany?: Prisma.dfw_accessScalarWhereInput | Prisma.dfw_accessScalarWhereInput[]
}

export type dfw_accessUncheckedUpdateManyWithoutCredentialsNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_accessCreateWithoutCredentialsInput, Prisma.dfw_accessUncheckedCreateWithoutCredentialsInput> | Prisma.dfw_accessCreateWithoutCredentialsInput[] | Prisma.dfw_accessUncheckedCreateWithoutCredentialsInput[]
  connectOrCreate?: Prisma.dfw_accessCreateOrConnectWithoutCredentialsInput | Prisma.dfw_accessCreateOrConnectWithoutCredentialsInput[]
  upsert?: Prisma.dfw_accessUpsertWithWhereUniqueWithoutCredentialsInput | Prisma.dfw_accessUpsertWithWhereUniqueWithoutCredentialsInput[]
  set?: Prisma.dfw_accessWhereUniqueInput | Prisma.dfw_accessWhereUniqueInput[]
  disconnect?: Prisma.dfw_accessWhereUniqueInput | Prisma.dfw_accessWhereUniqueInput[]
  delete?: Prisma.dfw_accessWhereUniqueInput | Prisma.dfw_accessWhereUniqueInput[]
  connect?: Prisma.dfw_accessWhereUniqueInput | Prisma.dfw_accessWhereUniqueInput[]
  update?: Prisma.dfw_accessUpdateWithWhereUniqueWithoutCredentialsInput | Prisma.dfw_accessUpdateWithWhereUniqueWithoutCredentialsInput[]
  updateMany?: Prisma.dfw_accessUpdateManyWithWhereWithoutCredentialsInput | Prisma.dfw_accessUpdateManyWithWhereWithoutCredentialsInput[]
  deleteMany?: Prisma.dfw_accessScalarWhereInput | Prisma.dfw_accessScalarWhereInput[]
}

export type dfw_accessCreateWithoutCredentialsInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type dfw_accessUncheckedCreateWithoutCredentialsInput = {
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type dfw_accessCreateOrConnectWithoutCredentialsInput = {
  where: Prisma.dfw_accessWhereUniqueInput
  create: Prisma.XOR<Prisma.dfw_accessCreateWithoutCredentialsInput, Prisma.dfw_accessUncheckedCreateWithoutCredentialsInput>
}

export type dfw_accessUpsertWithWhereUniqueWithoutCredentialsInput = {
  where: Prisma.dfw_accessWhereUniqueInput
  update: Prisma.XOR<Prisma.dfw_accessUpdateWithoutCredentialsInput, Prisma.dfw_accessUncheckedUpdateWithoutCredentialsInput>
  create: Prisma.XOR<Prisma.dfw_accessCreateWithoutCredentialsInput, Prisma.dfw_accessUncheckedCreateWithoutCredentialsInput>
}

export type dfw_accessUpdateWithWhereUniqueWithoutCredentialsInput = {
  where: Prisma.dfw_accessWhereUniqueInput
  data: Prisma.XOR<Prisma.dfw_accessUpdateWithoutCredentialsInput, Prisma.dfw_accessUncheckedUpdateWithoutCredentialsInput>
}

export type dfw_accessUpdateManyWithWhereWithoutCredentialsInput = {
  where: Prisma.dfw_accessScalarWhereInput
  data: Prisma.XOR<Prisma.dfw_accessUpdateManyMutationInput, Prisma.dfw_accessUncheckedUpdateManyWithoutCredentialsInput>
}

export type dfw_accessScalarWhereInput = {
  AND?: Prisma.dfw_accessScalarWhereInput | Prisma.dfw_accessScalarWhereInput[]
  OR?: Prisma.dfw_accessScalarWhereInput[]
  NOT?: Prisma.dfw_accessScalarWhereInput | Prisma.dfw_accessScalarWhereInput[]
  name?: Prisma.StringFilter<"dfw_access"> | string
  description?: Prisma.StringNullableFilter<"dfw_access"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_access"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_access"> | Date | string
}

export type dfw_accessUpdateWithoutCredentialsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_accessUncheckedUpdateWithoutCredentialsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_accessUncheckedUpdateManyWithoutCredentialsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type Dfw_accessCountOutputType
 */

export type Dfw_accessCountOutputType = {
  credentials: number
}

export type Dfw_accessCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  credentials?: boolean | Dfw_accessCountOutputTypeCountCredentialsArgs
}

/**
 * Dfw_accessCountOutputType without action
 */
export type Dfw_accessCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dfw_accessCountOutputType
   */
  select?: Prisma.Dfw_accessCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Dfw_accessCountOutputType without action
 */
export type Dfw_accessCountOutputTypeCountCredentialsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_credentialWhereInput
}


export type dfw_accessSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  credentials?: boolean | Prisma.dfw_access$credentialsArgs<ExtArgs>
  _count?: boolean | Prisma.Dfw_accessCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dfw_access"]>

export type dfw_accessSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dfw_access"]>

export type dfw_accessSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dfw_access"]>

export type dfw_accessSelectScalar = {
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type dfw_accessOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["dfw_access"]>
export type dfw_accessInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  credentials?: boolean | Prisma.dfw_access$credentialsArgs<ExtArgs>
  _count?: boolean | Prisma.Dfw_accessCountOutputTypeDefaultArgs<ExtArgs>
}
export type dfw_accessIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type dfw_accessIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $dfw_accessPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dfw_access"
  objects: {
    credentials: Prisma.$dfw_credentialPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    name: string
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dfw_access"]>
  composites: {}
}

export type dfw_accessGetPayload<S extends boolean | null | undefined | dfw_accessDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload, S>

export type dfw_accessCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dfw_accessFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Dfw_accessCountAggregateInputType | true
  }

export interface dfw_accessDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dfw_access'], meta: { name: 'dfw_access' } }
  /**
   * Find zero or one Dfw_access that matches the filter.
   * @param {dfw_accessFindUniqueArgs} args - Arguments to find a Dfw_access
   * @example
   * // Get one Dfw_access
   * const dfw_access = await prisma.dfw_access.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dfw_accessFindUniqueArgs>(args: Prisma.SelectSubset<T, dfw_accessFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dfw_accessClient<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dfw_access that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dfw_accessFindUniqueOrThrowArgs} args - Arguments to find a Dfw_access
   * @example
   * // Get one Dfw_access
   * const dfw_access = await prisma.dfw_access.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dfw_accessFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dfw_accessFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dfw_accessClient<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dfw_access that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_accessFindFirstArgs} args - Arguments to find a Dfw_access
   * @example
   * // Get one Dfw_access
   * const dfw_access = await prisma.dfw_access.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dfw_accessFindFirstArgs>(args?: Prisma.SelectSubset<T, dfw_accessFindFirstArgs<ExtArgs>>): Prisma.Prisma__dfw_accessClient<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dfw_access that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_accessFindFirstOrThrowArgs} args - Arguments to find a Dfw_access
   * @example
   * // Get one Dfw_access
   * const dfw_access = await prisma.dfw_access.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dfw_accessFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dfw_accessFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dfw_accessClient<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Dfw_accesses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_accessFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Dfw_accesses
   * const dfw_accesses = await prisma.dfw_access.findMany()
   * 
   * // Get first 10 Dfw_accesses
   * const dfw_accesses = await prisma.dfw_access.findMany({ take: 10 })
   * 
   * // Only select the `name`
   * const dfw_accessWithNameOnly = await prisma.dfw_access.findMany({ select: { name: true } })
   * 
   */
  findMany<T extends dfw_accessFindManyArgs>(args?: Prisma.SelectSubset<T, dfw_accessFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dfw_access.
   * @param {dfw_accessCreateArgs} args - Arguments to create a Dfw_access.
   * @example
   * // Create one Dfw_access
   * const Dfw_access = await prisma.dfw_access.create({
   *   data: {
   *     // ... data to create a Dfw_access
   *   }
   * })
   * 
   */
  create<T extends dfw_accessCreateArgs>(args: Prisma.SelectSubset<T, dfw_accessCreateArgs<ExtArgs>>): Prisma.Prisma__dfw_accessClient<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Dfw_accesses.
   * @param {dfw_accessCreateManyArgs} args - Arguments to create many Dfw_accesses.
   * @example
   * // Create many Dfw_accesses
   * const dfw_access = await prisma.dfw_access.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dfw_accessCreateManyArgs>(args?: Prisma.SelectSubset<T, dfw_accessCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Dfw_accesses and returns the data saved in the database.
   * @param {dfw_accessCreateManyAndReturnArgs} args - Arguments to create many Dfw_accesses.
   * @example
   * // Create many Dfw_accesses
   * const dfw_access = await prisma.dfw_access.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Dfw_accesses and only return the `name`
   * const dfw_accessWithNameOnly = await prisma.dfw_access.createManyAndReturn({
   *   select: { name: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends dfw_accessCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, dfw_accessCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Dfw_access.
   * @param {dfw_accessDeleteArgs} args - Arguments to delete one Dfw_access.
   * @example
   * // Delete one Dfw_access
   * const Dfw_access = await prisma.dfw_access.delete({
   *   where: {
   *     // ... filter to delete one Dfw_access
   *   }
   * })
   * 
   */
  delete<T extends dfw_accessDeleteArgs>(args: Prisma.SelectSubset<T, dfw_accessDeleteArgs<ExtArgs>>): Prisma.Prisma__dfw_accessClient<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dfw_access.
   * @param {dfw_accessUpdateArgs} args - Arguments to update one Dfw_access.
   * @example
   * // Update one Dfw_access
   * const dfw_access = await prisma.dfw_access.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dfw_accessUpdateArgs>(args: Prisma.SelectSubset<T, dfw_accessUpdateArgs<ExtArgs>>): Prisma.Prisma__dfw_accessClient<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Dfw_accesses.
   * @param {dfw_accessDeleteManyArgs} args - Arguments to filter Dfw_accesses to delete.
   * @example
   * // Delete a few Dfw_accesses
   * const { count } = await prisma.dfw_access.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dfw_accessDeleteManyArgs>(args?: Prisma.SelectSubset<T, dfw_accessDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dfw_accesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_accessUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Dfw_accesses
   * const dfw_access = await prisma.dfw_access.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dfw_accessUpdateManyArgs>(args: Prisma.SelectSubset<T, dfw_accessUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dfw_accesses and returns the data updated in the database.
   * @param {dfw_accessUpdateManyAndReturnArgs} args - Arguments to update many Dfw_accesses.
   * @example
   * // Update many Dfw_accesses
   * const dfw_access = await prisma.dfw_access.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Dfw_accesses and only return the `name`
   * const dfw_accessWithNameOnly = await prisma.dfw_access.updateManyAndReturn({
   *   select: { name: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends dfw_accessUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, dfw_accessUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Dfw_access.
   * @param {dfw_accessUpsertArgs} args - Arguments to update or create a Dfw_access.
   * @example
   * // Update or create a Dfw_access
   * const dfw_access = await prisma.dfw_access.upsert({
   *   create: {
   *     // ... data to create a Dfw_access
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dfw_access we want to update
   *   }
   * })
   */
  upsert<T extends dfw_accessUpsertArgs>(args: Prisma.SelectSubset<T, dfw_accessUpsertArgs<ExtArgs>>): Prisma.Prisma__dfw_accessClient<runtime.Types.Result.GetResult<Prisma.$dfw_accessPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Dfw_accesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_accessCountArgs} args - Arguments to filter Dfw_accesses to count.
   * @example
   * // Count the number of Dfw_accesses
   * const count = await prisma.dfw_access.count({
   *   where: {
   *     // ... the filter for the Dfw_accesses we want to count
   *   }
   * })
  **/
  count<T extends dfw_accessCountArgs>(
    args?: Prisma.Subset<T, dfw_accessCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Dfw_accessCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dfw_access.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Dfw_accessAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Dfw_accessAggregateArgs>(args: Prisma.Subset<T, Dfw_accessAggregateArgs>): Prisma.PrismaPromise<GetDfw_accessAggregateType<T>>

  /**
   * Group by Dfw_access.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_accessGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dfw_accessGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dfw_accessGroupByArgs['orderBy'] }
      : { orderBy?: dfw_accessGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dfw_accessGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDfw_accessGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dfw_access model
 */
readonly fields: dfw_accessFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dfw_access.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dfw_accessClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  credentials<T extends Prisma.dfw_access$credentialsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.dfw_access$credentialsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dfw_access model
 */
export interface dfw_accessFieldRefs {
  readonly name: Prisma.FieldRef<"dfw_access", 'String'>
  readonly description: Prisma.FieldRef<"dfw_access", 'String'>
  readonly createdAt: Prisma.FieldRef<"dfw_access", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"dfw_access", 'DateTime'>
}
    

// Custom InputTypes
/**
 * dfw_access findUnique
 */
export type dfw_accessFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
  /**
   * Filter, which dfw_access to fetch.
   */
  where: Prisma.dfw_accessWhereUniqueInput
}

/**
 * dfw_access findUniqueOrThrow
 */
export type dfw_accessFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
  /**
   * Filter, which dfw_access to fetch.
   */
  where: Prisma.dfw_accessWhereUniqueInput
}

/**
 * dfw_access findFirst
 */
export type dfw_accessFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
  /**
   * Filter, which dfw_access to fetch.
   */
  where?: Prisma.dfw_accessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_accesses to fetch.
   */
  orderBy?: Prisma.dfw_accessOrderByWithRelationInput | Prisma.dfw_accessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dfw_accesses.
   */
  cursor?: Prisma.dfw_accessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_accesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_accesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dfw_accesses.
   */
  distinct?: Prisma.Dfw_accessScalarFieldEnum | Prisma.Dfw_accessScalarFieldEnum[]
}

/**
 * dfw_access findFirstOrThrow
 */
export type dfw_accessFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
  /**
   * Filter, which dfw_access to fetch.
   */
  where?: Prisma.dfw_accessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_accesses to fetch.
   */
  orderBy?: Prisma.dfw_accessOrderByWithRelationInput | Prisma.dfw_accessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dfw_accesses.
   */
  cursor?: Prisma.dfw_accessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_accesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_accesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dfw_accesses.
   */
  distinct?: Prisma.Dfw_accessScalarFieldEnum | Prisma.Dfw_accessScalarFieldEnum[]
}

/**
 * dfw_access findMany
 */
export type dfw_accessFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
  /**
   * Filter, which dfw_accesses to fetch.
   */
  where?: Prisma.dfw_accessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_accesses to fetch.
   */
  orderBy?: Prisma.dfw_accessOrderByWithRelationInput | Prisma.dfw_accessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dfw_accesses.
   */
  cursor?: Prisma.dfw_accessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_accesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_accesses.
   */
  skip?: number
  distinct?: Prisma.Dfw_accessScalarFieldEnum | Prisma.Dfw_accessScalarFieldEnum[]
}

/**
 * dfw_access create
 */
export type dfw_accessCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
  /**
   * The data needed to create a dfw_access.
   */
  data: Prisma.XOR<Prisma.dfw_accessCreateInput, Prisma.dfw_accessUncheckedCreateInput>
}

/**
 * dfw_access createMany
 */
export type dfw_accessCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dfw_accesses.
   */
  data: Prisma.dfw_accessCreateManyInput | Prisma.dfw_accessCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dfw_access createManyAndReturn
 */
export type dfw_accessCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * The data used to create many dfw_accesses.
   */
  data: Prisma.dfw_accessCreateManyInput | Prisma.dfw_accessCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dfw_access update
 */
export type dfw_accessUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
  /**
   * The data needed to update a dfw_access.
   */
  data: Prisma.XOR<Prisma.dfw_accessUpdateInput, Prisma.dfw_accessUncheckedUpdateInput>
  /**
   * Choose, which dfw_access to update.
   */
  where: Prisma.dfw_accessWhereUniqueInput
}

/**
 * dfw_access updateMany
 */
export type dfw_accessUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dfw_accesses.
   */
  data: Prisma.XOR<Prisma.dfw_accessUpdateManyMutationInput, Prisma.dfw_accessUncheckedUpdateManyInput>
  /**
   * Filter which dfw_accesses to update
   */
  where?: Prisma.dfw_accessWhereInput
  /**
   * Limit how many dfw_accesses to update.
   */
  limit?: number
}

/**
 * dfw_access updateManyAndReturn
 */
export type dfw_accessUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * The data used to update dfw_accesses.
   */
  data: Prisma.XOR<Prisma.dfw_accessUpdateManyMutationInput, Prisma.dfw_accessUncheckedUpdateManyInput>
  /**
   * Filter which dfw_accesses to update
   */
  where?: Prisma.dfw_accessWhereInput
  /**
   * Limit how many dfw_accesses to update.
   */
  limit?: number
}

/**
 * dfw_access upsert
 */
export type dfw_accessUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
  /**
   * The filter to search for the dfw_access to update in case it exists.
   */
  where: Prisma.dfw_accessWhereUniqueInput
  /**
   * In case the dfw_access found by the `where` argument doesn't exist, create a new dfw_access with this data.
   */
  create: Prisma.XOR<Prisma.dfw_accessCreateInput, Prisma.dfw_accessUncheckedCreateInput>
  /**
   * In case the dfw_access was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dfw_accessUpdateInput, Prisma.dfw_accessUncheckedUpdateInput>
}

/**
 * dfw_access delete
 */
export type dfw_accessDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
  /**
   * Filter which dfw_access to delete.
   */
  where: Prisma.dfw_accessWhereUniqueInput
}

/**
 * dfw_access deleteMany
 */
export type dfw_accessDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dfw_accesses to delete
   */
  where?: Prisma.dfw_accessWhereInput
  /**
   * Limit how many dfw_accesses to delete.
   */
  limit?: number
}

/**
 * dfw_access.credentials
 */
export type dfw_access$credentialsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  where?: Prisma.dfw_credentialWhereInput
  orderBy?: Prisma.dfw_credentialOrderByWithRelationInput | Prisma.dfw_credentialOrderByWithRelationInput[]
  cursor?: Prisma.dfw_credentialWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Dfw_credentialScalarFieldEnum | Prisma.Dfw_credentialScalarFieldEnum[]
}

/**
 * dfw_access without action
 */
export type dfw_accessDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_access
   */
  select?: Prisma.dfw_accessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_access
   */
  omit?: Prisma.dfw_accessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_accessInclude<ExtArgs> | null
}
