
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dfw_session` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dfw_session
 * 
 */
export type dfw_sessionModel = runtime.Types.Result.DefaultSelection<Prisma.$dfw_sessionPayload>

export type AggregateDfw_session = {
  _count: Dfw_sessionCountAggregateOutputType | null
  _min: Dfw_sessionMinAggregateOutputType | null
  _max: Dfw_sessionMaxAggregateOutputType | null
}

export type Dfw_sessionMinAggregateOutputType = {
  id: string | null
  agent: string | null
  ip: string | null
  idUser: string | null
  createdAt: Date | null
  updatedAt: Date | null
  expiresAt: Date | null
}

export type Dfw_sessionMaxAggregateOutputType = {
  id: string | null
  agent: string | null
  ip: string | null
  idUser: string | null
  createdAt: Date | null
  updatedAt: Date | null
  expiresAt: Date | null
}

export type Dfw_sessionCountAggregateOutputType = {
  id: number
  agent: number
  ip: number
  idUser: number
  createdAt: number
  updatedAt: number
  expiresAt: number
  _all: number
}


export type Dfw_sessionMinAggregateInputType = {
  id?: true
  agent?: true
  ip?: true
  idUser?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
}

export type Dfw_sessionMaxAggregateInputType = {
  id?: true
  agent?: true
  ip?: true
  idUser?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
}

export type Dfw_sessionCountAggregateInputType = {
  id?: true
  agent?: true
  ip?: true
  idUser?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
  _all?: true
}

export type Dfw_sessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dfw_session to aggregate.
   */
  where?: Prisma.dfw_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_sessions to fetch.
   */
  orderBy?: Prisma.dfw_sessionOrderByWithRelationInput | Prisma.dfw_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dfw_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dfw_sessions
  **/
  _count?: true | Dfw_sessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Dfw_sessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Dfw_sessionMaxAggregateInputType
}

export type GetDfw_sessionAggregateType<T extends Dfw_sessionAggregateArgs> = {
      [P in keyof T & keyof AggregateDfw_session]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDfw_session[P]>
    : Prisma.GetScalarType<T[P], AggregateDfw_session[P]>
}




export type dfw_sessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_sessionWhereInput
  orderBy?: Prisma.dfw_sessionOrderByWithAggregationInput | Prisma.dfw_sessionOrderByWithAggregationInput[]
  by: Prisma.Dfw_sessionScalarFieldEnum[] | Prisma.Dfw_sessionScalarFieldEnum
  having?: Prisma.dfw_sessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Dfw_sessionCountAggregateInputType | true
  _min?: Dfw_sessionMinAggregateInputType
  _max?: Dfw_sessionMaxAggregateInputType
}

export type Dfw_sessionGroupByOutputType = {
  id: string
  agent: string | null
  ip: string | null
  idUser: string | null
  createdAt: Date
  updatedAt: Date
  expiresAt: Date | null
  _count: Dfw_sessionCountAggregateOutputType | null
  _min: Dfw_sessionMinAggregateOutputType | null
  _max: Dfw_sessionMaxAggregateOutputType | null
}

type GetDfw_sessionGroupByPayload<T extends dfw_sessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Dfw_sessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Dfw_sessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Dfw_sessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Dfw_sessionGroupByOutputType[P]>
      }
    >
  >



export type dfw_sessionWhereInput = {
  AND?: Prisma.dfw_sessionWhereInput | Prisma.dfw_sessionWhereInput[]
  OR?: Prisma.dfw_sessionWhereInput[]
  NOT?: Prisma.dfw_sessionWhereInput | Prisma.dfw_sessionWhereInput[]
  id?: Prisma.UuidFilter<"dfw_session"> | string
  agent?: Prisma.StringNullableFilter<"dfw_session"> | string | null
  ip?: Prisma.StringNullableFilter<"dfw_session"> | string | null
  idUser?: Prisma.StringNullableFilter<"dfw_session"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_session"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_session"> | Date | string
  expiresAt?: Prisma.DateTimeNullableFilter<"dfw_session"> | Date | string | null
  user?: Prisma.XOR<Prisma.Dfw_userNullableScalarRelationFilter, Prisma.dfw_userWhereInput> | null
}

export type dfw_sessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  agent?: Prisma.SortOrderInput | Prisma.SortOrder
  ip?: Prisma.SortOrderInput | Prisma.SortOrder
  idUser?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.dfw_userOrderByWithRelationInput
}

export type dfw_sessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.dfw_sessionWhereInput | Prisma.dfw_sessionWhereInput[]
  OR?: Prisma.dfw_sessionWhereInput[]
  NOT?: Prisma.dfw_sessionWhereInput | Prisma.dfw_sessionWhereInput[]
  agent?: Prisma.StringNullableFilter<"dfw_session"> | string | null
  ip?: Prisma.StringNullableFilter<"dfw_session"> | string | null
  idUser?: Prisma.StringNullableFilter<"dfw_session"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_session"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_session"> | Date | string
  expiresAt?: Prisma.DateTimeNullableFilter<"dfw_session"> | Date | string | null
  user?: Prisma.XOR<Prisma.Dfw_userNullableScalarRelationFilter, Prisma.dfw_userWhereInput> | null
}, "id">

export type dfw_sessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  agent?: Prisma.SortOrderInput | Prisma.SortOrder
  ip?: Prisma.SortOrderInput | Prisma.SortOrder
  idUser?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.dfw_sessionCountOrderByAggregateInput
  _max?: Prisma.dfw_sessionMaxOrderByAggregateInput
  _min?: Prisma.dfw_sessionMinOrderByAggregateInput
}

export type dfw_sessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.dfw_sessionScalarWhereWithAggregatesInput | Prisma.dfw_sessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.dfw_sessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dfw_sessionScalarWhereWithAggregatesInput | Prisma.dfw_sessionScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"dfw_session"> | string
  agent?: Prisma.StringNullableWithAggregatesFilter<"dfw_session"> | string | null
  ip?: Prisma.StringNullableWithAggregatesFilter<"dfw_session"> | string | null
  idUser?: Prisma.StringNullableWithAggregatesFilter<"dfw_session"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"dfw_session"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"dfw_session"> | Date | string
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"dfw_session"> | Date | string | null
}

export type dfw_sessionCreateInput = {
  id?: string
  agent?: string | null
  ip?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
  user?: Prisma.dfw_userCreateNestedOneWithoutSessionsInput
}

export type dfw_sessionUncheckedCreateInput = {
  id?: string
  agent?: string | null
  ip?: string | null
  idUser?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
}

export type dfw_sessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.dfw_userUpdateOneWithoutSessionsNestedInput
}

export type dfw_sessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  idUser?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type dfw_sessionCreateManyInput = {
  id?: string
  agent?: string | null
  ip?: string | null
  idUser?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
}

export type dfw_sessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type dfw_sessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  idUser?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Dfw_sessionListRelationFilter = {
  every?: Prisma.dfw_sessionWhereInput
  some?: Prisma.dfw_sessionWhereInput
  none?: Prisma.dfw_sessionWhereInput
}

export type dfw_sessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type dfw_sessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  agent?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type dfw_sessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  agent?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type dfw_sessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  agent?: Prisma.SortOrder
  ip?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type dfw_sessionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.dfw_sessionCreateWithoutUserInput, Prisma.dfw_sessionUncheckedCreateWithoutUserInput> | Prisma.dfw_sessionCreateWithoutUserInput[] | Prisma.dfw_sessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.dfw_sessionCreateOrConnectWithoutUserInput | Prisma.dfw_sessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.dfw_sessionCreateManyUserInputEnvelope
  connect?: Prisma.dfw_sessionWhereUniqueInput | Prisma.dfw_sessionWhereUniqueInput[]
}

export type dfw_sessionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.dfw_sessionCreateWithoutUserInput, Prisma.dfw_sessionUncheckedCreateWithoutUserInput> | Prisma.dfw_sessionCreateWithoutUserInput[] | Prisma.dfw_sessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.dfw_sessionCreateOrConnectWithoutUserInput | Prisma.dfw_sessionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.dfw_sessionCreateManyUserInputEnvelope
  connect?: Prisma.dfw_sessionWhereUniqueInput | Prisma.dfw_sessionWhereUniqueInput[]
}

export type dfw_sessionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_sessionCreateWithoutUserInput, Prisma.dfw_sessionUncheckedCreateWithoutUserInput> | Prisma.dfw_sessionCreateWithoutUserInput[] | Prisma.dfw_sessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.dfw_sessionCreateOrConnectWithoutUserInput | Prisma.dfw_sessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.dfw_sessionUpsertWithWhereUniqueWithoutUserInput | Prisma.dfw_sessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.dfw_sessionCreateManyUserInputEnvelope
  set?: Prisma.dfw_sessionWhereUniqueInput | Prisma.dfw_sessionWhereUniqueInput[]
  disconnect?: Prisma.dfw_sessionWhereUniqueInput | Prisma.dfw_sessionWhereUniqueInput[]
  delete?: Prisma.dfw_sessionWhereUniqueInput | Prisma.dfw_sessionWhereUniqueInput[]
  connect?: Prisma.dfw_sessionWhereUniqueInput | Prisma.dfw_sessionWhereUniqueInput[]
  update?: Prisma.dfw_sessionUpdateWithWhereUniqueWithoutUserInput | Prisma.dfw_sessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.dfw_sessionUpdateManyWithWhereWithoutUserInput | Prisma.dfw_sessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.dfw_sessionScalarWhereInput | Prisma.dfw_sessionScalarWhereInput[]
}

export type dfw_sessionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_sessionCreateWithoutUserInput, Prisma.dfw_sessionUncheckedCreateWithoutUserInput> | Prisma.dfw_sessionCreateWithoutUserInput[] | Prisma.dfw_sessionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.dfw_sessionCreateOrConnectWithoutUserInput | Prisma.dfw_sessionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.dfw_sessionUpsertWithWhereUniqueWithoutUserInput | Prisma.dfw_sessionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.dfw_sessionCreateManyUserInputEnvelope
  set?: Prisma.dfw_sessionWhereUniqueInput | Prisma.dfw_sessionWhereUniqueInput[]
  disconnect?: Prisma.dfw_sessionWhereUniqueInput | Prisma.dfw_sessionWhereUniqueInput[]
  delete?: Prisma.dfw_sessionWhereUniqueInput | Prisma.dfw_sessionWhereUniqueInput[]
  connect?: Prisma.dfw_sessionWhereUniqueInput | Prisma.dfw_sessionWhereUniqueInput[]
  update?: Prisma.dfw_sessionUpdateWithWhereUniqueWithoutUserInput | Prisma.dfw_sessionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.dfw_sessionUpdateManyWithWhereWithoutUserInput | Prisma.dfw_sessionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.dfw_sessionScalarWhereInput | Prisma.dfw_sessionScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type dfw_sessionCreateWithoutUserInput = {
  id?: string
  agent?: string | null
  ip?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
}

export type dfw_sessionUncheckedCreateWithoutUserInput = {
  id?: string
  agent?: string | null
  ip?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
}

export type dfw_sessionCreateOrConnectWithoutUserInput = {
  where: Prisma.dfw_sessionWhereUniqueInput
  create: Prisma.XOR<Prisma.dfw_sessionCreateWithoutUserInput, Prisma.dfw_sessionUncheckedCreateWithoutUserInput>
}

export type dfw_sessionCreateManyUserInputEnvelope = {
  data: Prisma.dfw_sessionCreateManyUserInput | Prisma.dfw_sessionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type dfw_sessionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.dfw_sessionWhereUniqueInput
  update: Prisma.XOR<Prisma.dfw_sessionUpdateWithoutUserInput, Prisma.dfw_sessionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.dfw_sessionCreateWithoutUserInput, Prisma.dfw_sessionUncheckedCreateWithoutUserInput>
}

export type dfw_sessionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.dfw_sessionWhereUniqueInput
  data: Prisma.XOR<Prisma.dfw_sessionUpdateWithoutUserInput, Prisma.dfw_sessionUncheckedUpdateWithoutUserInput>
}

export type dfw_sessionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.dfw_sessionScalarWhereInput
  data: Prisma.XOR<Prisma.dfw_sessionUpdateManyMutationInput, Prisma.dfw_sessionUncheckedUpdateManyWithoutUserInput>
}

export type dfw_sessionScalarWhereInput = {
  AND?: Prisma.dfw_sessionScalarWhereInput | Prisma.dfw_sessionScalarWhereInput[]
  OR?: Prisma.dfw_sessionScalarWhereInput[]
  NOT?: Prisma.dfw_sessionScalarWhereInput | Prisma.dfw_sessionScalarWhereInput[]
  id?: Prisma.UuidFilter<"dfw_session"> | string
  agent?: Prisma.StringNullableFilter<"dfw_session"> | string | null
  ip?: Prisma.StringNullableFilter<"dfw_session"> | string | null
  idUser?: Prisma.StringNullableFilter<"dfw_session"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_session"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_session"> | Date | string
  expiresAt?: Prisma.DateTimeNullableFilter<"dfw_session"> | Date | string | null
}

export type dfw_sessionCreateManyUserInput = {
  id?: string
  agent?: string | null
  ip?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
}

export type dfw_sessionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type dfw_sessionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type dfw_sessionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type dfw_sessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  agent?: boolean
  ip?: boolean
  idUser?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
  user?: boolean | Prisma.dfw_session$userArgs<ExtArgs>
}, ExtArgs["result"]["dfw_session"]>

export type dfw_sessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  agent?: boolean
  ip?: boolean
  idUser?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
  user?: boolean | Prisma.dfw_session$userArgs<ExtArgs>
}, ExtArgs["result"]["dfw_session"]>

export type dfw_sessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  agent?: boolean
  ip?: boolean
  idUser?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
  user?: boolean | Prisma.dfw_session$userArgs<ExtArgs>
}, ExtArgs["result"]["dfw_session"]>

export type dfw_sessionSelectScalar = {
  id?: boolean
  agent?: boolean
  ip?: boolean
  idUser?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
}

export type dfw_sessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "agent" | "ip" | "idUser" | "createdAt" | "updatedAt" | "expiresAt", ExtArgs["result"]["dfw_session"]>
export type dfw_sessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.dfw_session$userArgs<ExtArgs>
}
export type dfw_sessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.dfw_session$userArgs<ExtArgs>
}
export type dfw_sessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.dfw_session$userArgs<ExtArgs>
}

export type $dfw_sessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dfw_session"
  objects: {
    user: Prisma.$dfw_userPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    agent: string | null
    ip: string | null
    idUser: string | null
    createdAt: Date
    updatedAt: Date
    expiresAt: Date | null
  }, ExtArgs["result"]["dfw_session"]>
  composites: {}
}

export type dfw_sessionGetPayload<S extends boolean | null | undefined | dfw_sessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload, S>

export type dfw_sessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dfw_sessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Dfw_sessionCountAggregateInputType | true
  }

export interface dfw_sessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dfw_session'], meta: { name: 'dfw_session' } }
  /**
   * Find zero or one Dfw_session that matches the filter.
   * @param {dfw_sessionFindUniqueArgs} args - Arguments to find a Dfw_session
   * @example
   * // Get one Dfw_session
   * const dfw_session = await prisma.dfw_session.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dfw_sessionFindUniqueArgs>(args: Prisma.SelectSubset<T, dfw_sessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dfw_sessionClient<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dfw_session that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dfw_sessionFindUniqueOrThrowArgs} args - Arguments to find a Dfw_session
   * @example
   * // Get one Dfw_session
   * const dfw_session = await prisma.dfw_session.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dfw_sessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dfw_sessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dfw_sessionClient<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dfw_session that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_sessionFindFirstArgs} args - Arguments to find a Dfw_session
   * @example
   * // Get one Dfw_session
   * const dfw_session = await prisma.dfw_session.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dfw_sessionFindFirstArgs>(args?: Prisma.SelectSubset<T, dfw_sessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__dfw_sessionClient<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dfw_session that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_sessionFindFirstOrThrowArgs} args - Arguments to find a Dfw_session
   * @example
   * // Get one Dfw_session
   * const dfw_session = await prisma.dfw_session.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dfw_sessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dfw_sessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dfw_sessionClient<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Dfw_sessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_sessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Dfw_sessions
   * const dfw_sessions = await prisma.dfw_session.findMany()
   * 
   * // Get first 10 Dfw_sessions
   * const dfw_sessions = await prisma.dfw_session.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dfw_sessionWithIdOnly = await prisma.dfw_session.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends dfw_sessionFindManyArgs>(args?: Prisma.SelectSubset<T, dfw_sessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dfw_session.
   * @param {dfw_sessionCreateArgs} args - Arguments to create a Dfw_session.
   * @example
   * // Create one Dfw_session
   * const Dfw_session = await prisma.dfw_session.create({
   *   data: {
   *     // ... data to create a Dfw_session
   *   }
   * })
   * 
   */
  create<T extends dfw_sessionCreateArgs>(args: Prisma.SelectSubset<T, dfw_sessionCreateArgs<ExtArgs>>): Prisma.Prisma__dfw_sessionClient<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Dfw_sessions.
   * @param {dfw_sessionCreateManyArgs} args - Arguments to create many Dfw_sessions.
   * @example
   * // Create many Dfw_sessions
   * const dfw_session = await prisma.dfw_session.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dfw_sessionCreateManyArgs>(args?: Prisma.SelectSubset<T, dfw_sessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Dfw_sessions and returns the data saved in the database.
   * @param {dfw_sessionCreateManyAndReturnArgs} args - Arguments to create many Dfw_sessions.
   * @example
   * // Create many Dfw_sessions
   * const dfw_session = await prisma.dfw_session.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Dfw_sessions and only return the `id`
   * const dfw_sessionWithIdOnly = await prisma.dfw_session.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends dfw_sessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, dfw_sessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Dfw_session.
   * @param {dfw_sessionDeleteArgs} args - Arguments to delete one Dfw_session.
   * @example
   * // Delete one Dfw_session
   * const Dfw_session = await prisma.dfw_session.delete({
   *   where: {
   *     // ... filter to delete one Dfw_session
   *   }
   * })
   * 
   */
  delete<T extends dfw_sessionDeleteArgs>(args: Prisma.SelectSubset<T, dfw_sessionDeleteArgs<ExtArgs>>): Prisma.Prisma__dfw_sessionClient<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dfw_session.
   * @param {dfw_sessionUpdateArgs} args - Arguments to update one Dfw_session.
   * @example
   * // Update one Dfw_session
   * const dfw_session = await prisma.dfw_session.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dfw_sessionUpdateArgs>(args: Prisma.SelectSubset<T, dfw_sessionUpdateArgs<ExtArgs>>): Prisma.Prisma__dfw_sessionClient<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Dfw_sessions.
   * @param {dfw_sessionDeleteManyArgs} args - Arguments to filter Dfw_sessions to delete.
   * @example
   * // Delete a few Dfw_sessions
   * const { count } = await prisma.dfw_session.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dfw_sessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, dfw_sessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dfw_sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_sessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Dfw_sessions
   * const dfw_session = await prisma.dfw_session.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dfw_sessionUpdateManyArgs>(args: Prisma.SelectSubset<T, dfw_sessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dfw_sessions and returns the data updated in the database.
   * @param {dfw_sessionUpdateManyAndReturnArgs} args - Arguments to update many Dfw_sessions.
   * @example
   * // Update many Dfw_sessions
   * const dfw_session = await prisma.dfw_session.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Dfw_sessions and only return the `id`
   * const dfw_sessionWithIdOnly = await prisma.dfw_session.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends dfw_sessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, dfw_sessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Dfw_session.
   * @param {dfw_sessionUpsertArgs} args - Arguments to update or create a Dfw_session.
   * @example
   * // Update or create a Dfw_session
   * const dfw_session = await prisma.dfw_session.upsert({
   *   create: {
   *     // ... data to create a Dfw_session
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dfw_session we want to update
   *   }
   * })
   */
  upsert<T extends dfw_sessionUpsertArgs>(args: Prisma.SelectSubset<T, dfw_sessionUpsertArgs<ExtArgs>>): Prisma.Prisma__dfw_sessionClient<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Dfw_sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_sessionCountArgs} args - Arguments to filter Dfw_sessions to count.
   * @example
   * // Count the number of Dfw_sessions
   * const count = await prisma.dfw_session.count({
   *   where: {
   *     // ... the filter for the Dfw_sessions we want to count
   *   }
   * })
  **/
  count<T extends dfw_sessionCountArgs>(
    args?: Prisma.Subset<T, dfw_sessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Dfw_sessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dfw_session.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Dfw_sessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Dfw_sessionAggregateArgs>(args: Prisma.Subset<T, Dfw_sessionAggregateArgs>): Prisma.PrismaPromise<GetDfw_sessionAggregateType<T>>

  /**
   * Group by Dfw_session.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_sessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dfw_sessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dfw_sessionGroupByArgs['orderBy'] }
      : { orderBy?: dfw_sessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dfw_sessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDfw_sessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dfw_session model
 */
readonly fields: dfw_sessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dfw_session.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dfw_sessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.dfw_session$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.dfw_session$userArgs<ExtArgs>>): Prisma.Prisma__dfw_userClient<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dfw_session model
 */
export interface dfw_sessionFieldRefs {
  readonly id: Prisma.FieldRef<"dfw_session", 'String'>
  readonly agent: Prisma.FieldRef<"dfw_session", 'String'>
  readonly ip: Prisma.FieldRef<"dfw_session", 'String'>
  readonly idUser: Prisma.FieldRef<"dfw_session", 'String'>
  readonly createdAt: Prisma.FieldRef<"dfw_session", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"dfw_session", 'DateTime'>
  readonly expiresAt: Prisma.FieldRef<"dfw_session", 'DateTime'>
}
    

// Custom InputTypes
/**
 * dfw_session findUnique
 */
export type dfw_sessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
  /**
   * Filter, which dfw_session to fetch.
   */
  where: Prisma.dfw_sessionWhereUniqueInput
}

/**
 * dfw_session findUniqueOrThrow
 */
export type dfw_sessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
  /**
   * Filter, which dfw_session to fetch.
   */
  where: Prisma.dfw_sessionWhereUniqueInput
}

/**
 * dfw_session findFirst
 */
export type dfw_sessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
  /**
   * Filter, which dfw_session to fetch.
   */
  where?: Prisma.dfw_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_sessions to fetch.
   */
  orderBy?: Prisma.dfw_sessionOrderByWithRelationInput | Prisma.dfw_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dfw_sessions.
   */
  cursor?: Prisma.dfw_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dfw_sessions.
   */
  distinct?: Prisma.Dfw_sessionScalarFieldEnum | Prisma.Dfw_sessionScalarFieldEnum[]
}

/**
 * dfw_session findFirstOrThrow
 */
export type dfw_sessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
  /**
   * Filter, which dfw_session to fetch.
   */
  where?: Prisma.dfw_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_sessions to fetch.
   */
  orderBy?: Prisma.dfw_sessionOrderByWithRelationInput | Prisma.dfw_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dfw_sessions.
   */
  cursor?: Prisma.dfw_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dfw_sessions.
   */
  distinct?: Prisma.Dfw_sessionScalarFieldEnum | Prisma.Dfw_sessionScalarFieldEnum[]
}

/**
 * dfw_session findMany
 */
export type dfw_sessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
  /**
   * Filter, which dfw_sessions to fetch.
   */
  where?: Prisma.dfw_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_sessions to fetch.
   */
  orderBy?: Prisma.dfw_sessionOrderByWithRelationInput | Prisma.dfw_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dfw_sessions.
   */
  cursor?: Prisma.dfw_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_sessions.
   */
  skip?: number
  distinct?: Prisma.Dfw_sessionScalarFieldEnum | Prisma.Dfw_sessionScalarFieldEnum[]
}

/**
 * dfw_session create
 */
export type dfw_sessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
  /**
   * The data needed to create a dfw_session.
   */
  data: Prisma.XOR<Prisma.dfw_sessionCreateInput, Prisma.dfw_sessionUncheckedCreateInput>
}

/**
 * dfw_session createMany
 */
export type dfw_sessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dfw_sessions.
   */
  data: Prisma.dfw_sessionCreateManyInput | Prisma.dfw_sessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dfw_session createManyAndReturn
 */
export type dfw_sessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * The data used to create many dfw_sessions.
   */
  data: Prisma.dfw_sessionCreateManyInput | Prisma.dfw_sessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * dfw_session update
 */
export type dfw_sessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
  /**
   * The data needed to update a dfw_session.
   */
  data: Prisma.XOR<Prisma.dfw_sessionUpdateInput, Prisma.dfw_sessionUncheckedUpdateInput>
  /**
   * Choose, which dfw_session to update.
   */
  where: Prisma.dfw_sessionWhereUniqueInput
}

/**
 * dfw_session updateMany
 */
export type dfw_sessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dfw_sessions.
   */
  data: Prisma.XOR<Prisma.dfw_sessionUpdateManyMutationInput, Prisma.dfw_sessionUncheckedUpdateManyInput>
  /**
   * Filter which dfw_sessions to update
   */
  where?: Prisma.dfw_sessionWhereInput
  /**
   * Limit how many dfw_sessions to update.
   */
  limit?: number
}

/**
 * dfw_session updateManyAndReturn
 */
export type dfw_sessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * The data used to update dfw_sessions.
   */
  data: Prisma.XOR<Prisma.dfw_sessionUpdateManyMutationInput, Prisma.dfw_sessionUncheckedUpdateManyInput>
  /**
   * Filter which dfw_sessions to update
   */
  where?: Prisma.dfw_sessionWhereInput
  /**
   * Limit how many dfw_sessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * dfw_session upsert
 */
export type dfw_sessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
  /**
   * The filter to search for the dfw_session to update in case it exists.
   */
  where: Prisma.dfw_sessionWhereUniqueInput
  /**
   * In case the dfw_session found by the `where` argument doesn't exist, create a new dfw_session with this data.
   */
  create: Prisma.XOR<Prisma.dfw_sessionCreateInput, Prisma.dfw_sessionUncheckedCreateInput>
  /**
   * In case the dfw_session was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dfw_sessionUpdateInput, Prisma.dfw_sessionUncheckedUpdateInput>
}

/**
 * dfw_session delete
 */
export type dfw_sessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
  /**
   * Filter which dfw_session to delete.
   */
  where: Prisma.dfw_sessionWhereUniqueInput
}

/**
 * dfw_session deleteMany
 */
export type dfw_sessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dfw_sessions to delete
   */
  where?: Prisma.dfw_sessionWhereInput
  /**
   * Limit how many dfw_sessions to delete.
   */
  limit?: number
}

/**
 * dfw_session.user
 */
export type dfw_session$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  where?: Prisma.dfw_userWhereInput
}

/**
 * dfw_session without action
 */
export type dfw_sessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
}
