
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `dfw_user` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model dfw_user
 * 
 */
export type dfw_userModel = runtime.Types.Result.DefaultSelection<Prisma.$dfw_userPayload>

export type AggregateDfw_user = {
  _count: Dfw_userCountAggregateOutputType | null
  _min: Dfw_userMinAggregateOutputType | null
  _max: Dfw_userMaxAggregateOutputType | null
}

export type Dfw_userMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  displayName: string | null
  encodedKey: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Dfw_userMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  displayName: string | null
  encodedKey: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Dfw_userCountAggregateOutputType = {
  id: number
  name: number
  email: number
  displayName: number
  encodedKey: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type Dfw_userMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  displayName?: true
  encodedKey?: true
  createdAt?: true
  updatedAt?: true
}

export type Dfw_userMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  displayName?: true
  encodedKey?: true
  createdAt?: true
  updatedAt?: true
}

export type Dfw_userCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  displayName?: true
  encodedKey?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type Dfw_userAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dfw_user to aggregate.
   */
  where?: Prisma.dfw_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_users to fetch.
   */
  orderBy?: Prisma.dfw_userOrderByWithRelationInput | Prisma.dfw_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.dfw_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned dfw_users
  **/
  _count?: true | Dfw_userCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Dfw_userMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Dfw_userMaxAggregateInputType
}

export type GetDfw_userAggregateType<T extends Dfw_userAggregateArgs> = {
      [P in keyof T & keyof AggregateDfw_user]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDfw_user[P]>
    : Prisma.GetScalarType<T[P], AggregateDfw_user[P]>
}




export type dfw_userGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_userWhereInput
  orderBy?: Prisma.dfw_userOrderByWithAggregationInput | Prisma.dfw_userOrderByWithAggregationInput[]
  by: Prisma.Dfw_userScalarFieldEnum[] | Prisma.Dfw_userScalarFieldEnum
  having?: Prisma.dfw_userScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Dfw_userCountAggregateInputType | true
  _min?: Dfw_userMinAggregateInputType
  _max?: Dfw_userMaxAggregateInputType
}

export type Dfw_userGroupByOutputType = {
  id: string
  name: string | null
  email: string | null
  displayName: string | null
  encodedKey: string | null
  createdAt: Date
  updatedAt: Date
  _count: Dfw_userCountAggregateOutputType | null
  _min: Dfw_userMinAggregateOutputType | null
  _max: Dfw_userMaxAggregateOutputType | null
}

type GetDfw_userGroupByPayload<T extends dfw_userGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Dfw_userGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Dfw_userGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Dfw_userGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Dfw_userGroupByOutputType[P]>
      }
    >
  >



export type dfw_userWhereInput = {
  AND?: Prisma.dfw_userWhereInput | Prisma.dfw_userWhereInput[]
  OR?: Prisma.dfw_userWhereInput[]
  NOT?: Prisma.dfw_userWhereInput | Prisma.dfw_userWhereInput[]
  id?: Prisma.StringFilter<"dfw_user"> | string
  name?: Prisma.StringNullableFilter<"dfw_user"> | string | null
  email?: Prisma.StringNullableFilter<"dfw_user"> | string | null
  displayName?: Prisma.StringNullableFilter<"dfw_user"> | string | null
  encodedKey?: Prisma.StringNullableFilter<"dfw_user"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_user"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_user"> | Date | string
  credentials?: Prisma.Dfw_credentialListRelationFilter
  files?: Prisma.Dfw_fileListRelationFilter
  sessions?: Prisma.Dfw_sessionListRelationFilter
}

export type dfw_userOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  displayName?: Prisma.SortOrderInput | Prisma.SortOrder
  encodedKey?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  credentials?: Prisma.dfw_credentialOrderByRelationAggregateInput
  files?: Prisma.dfw_fileOrderByRelationAggregateInput
  sessions?: Prisma.dfw_sessionOrderByRelationAggregateInput
}

export type dfw_userWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  email?: string
  AND?: Prisma.dfw_userWhereInput | Prisma.dfw_userWhereInput[]
  OR?: Prisma.dfw_userWhereInput[]
  NOT?: Prisma.dfw_userWhereInput | Prisma.dfw_userWhereInput[]
  displayName?: Prisma.StringNullableFilter<"dfw_user"> | string | null
  encodedKey?: Prisma.StringNullableFilter<"dfw_user"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_user"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_user"> | Date | string
  credentials?: Prisma.Dfw_credentialListRelationFilter
  files?: Prisma.Dfw_fileListRelationFilter
  sessions?: Prisma.Dfw_sessionListRelationFilter
}, "id" | "name" | "email">

export type dfw_userOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  displayName?: Prisma.SortOrderInput | Prisma.SortOrder
  encodedKey?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.dfw_userCountOrderByAggregateInput
  _max?: Prisma.dfw_userMaxOrderByAggregateInput
  _min?: Prisma.dfw_userMinOrderByAggregateInput
}

export type dfw_userScalarWhereWithAggregatesInput = {
  AND?: Prisma.dfw_userScalarWhereWithAggregatesInput | Prisma.dfw_userScalarWhereWithAggregatesInput[]
  OR?: Prisma.dfw_userScalarWhereWithAggregatesInput[]
  NOT?: Prisma.dfw_userScalarWhereWithAggregatesInput | Prisma.dfw_userScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"dfw_user"> | string
  name?: Prisma.StringNullableWithAggregatesFilter<"dfw_user"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"dfw_user"> | string | null
  displayName?: Prisma.StringNullableWithAggregatesFilter<"dfw_user"> | string | null
  encodedKey?: Prisma.StringNullableWithAggregatesFilter<"dfw_user"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"dfw_user"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"dfw_user"> | Date | string
}

export type dfw_userCreateInput = {
  id?: string
  name?: string | null
  email?: string | null
  displayName?: string | null
  encodedKey?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  credentials?: Prisma.dfw_credentialCreateNestedManyWithoutUsersInput
  files?: Prisma.dfw_fileCreateNestedManyWithoutUserInput
  sessions?: Prisma.dfw_sessionCreateNestedManyWithoutUserInput
}

export type dfw_userUncheckedCreateInput = {
  id?: string
  name?: string | null
  email?: string | null
  displayName?: string | null
  encodedKey?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  credentials?: Prisma.dfw_credentialUncheckedCreateNestedManyWithoutUsersInput
  files?: Prisma.dfw_fileUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.dfw_sessionUncheckedCreateNestedManyWithoutUserInput
}

export type dfw_userUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  credentials?: Prisma.dfw_credentialUpdateManyWithoutUsersNestedInput
  files?: Prisma.dfw_fileUpdateManyWithoutUserNestedInput
  sessions?: Prisma.dfw_sessionUpdateManyWithoutUserNestedInput
}

export type dfw_userUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  credentials?: Prisma.dfw_credentialUncheckedUpdateManyWithoutUsersNestedInput
  files?: Prisma.dfw_fileUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.dfw_sessionUncheckedUpdateManyWithoutUserNestedInput
}

export type dfw_userCreateManyInput = {
  id?: string
  name?: string | null
  email?: string | null
  displayName?: string | null
  encodedKey?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type dfw_userUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_userUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type dfw_userCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  encodedKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type dfw_userMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  encodedKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type dfw_userMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  encodedKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type Dfw_userNullableScalarRelationFilter = {
  is?: Prisma.dfw_userWhereInput | null
  isNot?: Prisma.dfw_userWhereInput | null
}

export type Dfw_userListRelationFilter = {
  every?: Prisma.dfw_userWhereInput
  some?: Prisma.dfw_userWhereInput
  none?: Prisma.dfw_userWhereInput
}

export type dfw_userOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type dfw_userCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.dfw_userCreateWithoutSessionsInput, Prisma.dfw_userUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.dfw_userCreateOrConnectWithoutSessionsInput
  connect?: Prisma.dfw_userWhereUniqueInput
}

export type dfw_userUpdateOneWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_userCreateWithoutSessionsInput, Prisma.dfw_userUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.dfw_userCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.dfw_userUpsertWithoutSessionsInput
  disconnect?: Prisma.dfw_userWhereInput | boolean
  delete?: Prisma.dfw_userWhereInput | boolean
  connect?: Prisma.dfw_userWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.dfw_userUpdateToOneWithWhereWithoutSessionsInput, Prisma.dfw_userUpdateWithoutSessionsInput>, Prisma.dfw_userUncheckedUpdateWithoutSessionsInput>
}

export type dfw_userCreateNestedManyWithoutCredentialsInput = {
  create?: Prisma.XOR<Prisma.dfw_userCreateWithoutCredentialsInput, Prisma.dfw_userUncheckedCreateWithoutCredentialsInput> | Prisma.dfw_userCreateWithoutCredentialsInput[] | Prisma.dfw_userUncheckedCreateWithoutCredentialsInput[]
  connectOrCreate?: Prisma.dfw_userCreateOrConnectWithoutCredentialsInput | Prisma.dfw_userCreateOrConnectWithoutCredentialsInput[]
  connect?: Prisma.dfw_userWhereUniqueInput | Prisma.dfw_userWhereUniqueInput[]
}

export type dfw_userUncheckedCreateNestedManyWithoutCredentialsInput = {
  create?: Prisma.XOR<Prisma.dfw_userCreateWithoutCredentialsInput, Prisma.dfw_userUncheckedCreateWithoutCredentialsInput> | Prisma.dfw_userCreateWithoutCredentialsInput[] | Prisma.dfw_userUncheckedCreateWithoutCredentialsInput[]
  connectOrCreate?: Prisma.dfw_userCreateOrConnectWithoutCredentialsInput | Prisma.dfw_userCreateOrConnectWithoutCredentialsInput[]
  connect?: Prisma.dfw_userWhereUniqueInput | Prisma.dfw_userWhereUniqueInput[]
}

export type dfw_userUpdateManyWithoutCredentialsNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_userCreateWithoutCredentialsInput, Prisma.dfw_userUncheckedCreateWithoutCredentialsInput> | Prisma.dfw_userCreateWithoutCredentialsInput[] | Prisma.dfw_userUncheckedCreateWithoutCredentialsInput[]
  connectOrCreate?: Prisma.dfw_userCreateOrConnectWithoutCredentialsInput | Prisma.dfw_userCreateOrConnectWithoutCredentialsInput[]
  upsert?: Prisma.dfw_userUpsertWithWhereUniqueWithoutCredentialsInput | Prisma.dfw_userUpsertWithWhereUniqueWithoutCredentialsInput[]
  set?: Prisma.dfw_userWhereUniqueInput | Prisma.dfw_userWhereUniqueInput[]
  disconnect?: Prisma.dfw_userWhereUniqueInput | Prisma.dfw_userWhereUniqueInput[]
  delete?: Prisma.dfw_userWhereUniqueInput | Prisma.dfw_userWhereUniqueInput[]
  connect?: Prisma.dfw_userWhereUniqueInput | Prisma.dfw_userWhereUniqueInput[]
  update?: Prisma.dfw_userUpdateWithWhereUniqueWithoutCredentialsInput | Prisma.dfw_userUpdateWithWhereUniqueWithoutCredentialsInput[]
  updateMany?: Prisma.dfw_userUpdateManyWithWhereWithoutCredentialsInput | Prisma.dfw_userUpdateManyWithWhereWithoutCredentialsInput[]
  deleteMany?: Prisma.dfw_userScalarWhereInput | Prisma.dfw_userScalarWhereInput[]
}

export type dfw_userUncheckedUpdateManyWithoutCredentialsNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_userCreateWithoutCredentialsInput, Prisma.dfw_userUncheckedCreateWithoutCredentialsInput> | Prisma.dfw_userCreateWithoutCredentialsInput[] | Prisma.dfw_userUncheckedCreateWithoutCredentialsInput[]
  connectOrCreate?: Prisma.dfw_userCreateOrConnectWithoutCredentialsInput | Prisma.dfw_userCreateOrConnectWithoutCredentialsInput[]
  upsert?: Prisma.dfw_userUpsertWithWhereUniqueWithoutCredentialsInput | Prisma.dfw_userUpsertWithWhereUniqueWithoutCredentialsInput[]
  set?: Prisma.dfw_userWhereUniqueInput | Prisma.dfw_userWhereUniqueInput[]
  disconnect?: Prisma.dfw_userWhereUniqueInput | Prisma.dfw_userWhereUniqueInput[]
  delete?: Prisma.dfw_userWhereUniqueInput | Prisma.dfw_userWhereUniqueInput[]
  connect?: Prisma.dfw_userWhereUniqueInput | Prisma.dfw_userWhereUniqueInput[]
  update?: Prisma.dfw_userUpdateWithWhereUniqueWithoutCredentialsInput | Prisma.dfw_userUpdateWithWhereUniqueWithoutCredentialsInput[]
  updateMany?: Prisma.dfw_userUpdateManyWithWhereWithoutCredentialsInput | Prisma.dfw_userUpdateManyWithWhereWithoutCredentialsInput[]
  deleteMany?: Prisma.dfw_userScalarWhereInput | Prisma.dfw_userScalarWhereInput[]
}

export type dfw_userCreateNestedOneWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.dfw_userCreateWithoutFilesInput, Prisma.dfw_userUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.dfw_userCreateOrConnectWithoutFilesInput
  connect?: Prisma.dfw_userWhereUniqueInput
}

export type dfw_userUpdateOneWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.dfw_userCreateWithoutFilesInput, Prisma.dfw_userUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.dfw_userCreateOrConnectWithoutFilesInput
  upsert?: Prisma.dfw_userUpsertWithoutFilesInput
  disconnect?: Prisma.dfw_userWhereInput | boolean
  delete?: Prisma.dfw_userWhereInput | boolean
  connect?: Prisma.dfw_userWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.dfw_userUpdateToOneWithWhereWithoutFilesInput, Prisma.dfw_userUpdateWithoutFilesInput>, Prisma.dfw_userUncheckedUpdateWithoutFilesInput>
}

export type dfw_userCreateWithoutSessionsInput = {
  id?: string
  name?: string | null
  email?: string | null
  displayName?: string | null
  encodedKey?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  credentials?: Prisma.dfw_credentialCreateNestedManyWithoutUsersInput
  files?: Prisma.dfw_fileCreateNestedManyWithoutUserInput
}

export type dfw_userUncheckedCreateWithoutSessionsInput = {
  id?: string
  name?: string | null
  email?: string | null
  displayName?: string | null
  encodedKey?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  credentials?: Prisma.dfw_credentialUncheckedCreateNestedManyWithoutUsersInput
  files?: Prisma.dfw_fileUncheckedCreateNestedManyWithoutUserInput
}

export type dfw_userCreateOrConnectWithoutSessionsInput = {
  where: Prisma.dfw_userWhereUniqueInput
  create: Prisma.XOR<Prisma.dfw_userCreateWithoutSessionsInput, Prisma.dfw_userUncheckedCreateWithoutSessionsInput>
}

export type dfw_userUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.dfw_userUpdateWithoutSessionsInput, Prisma.dfw_userUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.dfw_userCreateWithoutSessionsInput, Prisma.dfw_userUncheckedCreateWithoutSessionsInput>
  where?: Prisma.dfw_userWhereInput
}

export type dfw_userUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.dfw_userWhereInput
  data: Prisma.XOR<Prisma.dfw_userUpdateWithoutSessionsInput, Prisma.dfw_userUncheckedUpdateWithoutSessionsInput>
}

export type dfw_userUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  credentials?: Prisma.dfw_credentialUpdateManyWithoutUsersNestedInput
  files?: Prisma.dfw_fileUpdateManyWithoutUserNestedInput
}

export type dfw_userUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  credentials?: Prisma.dfw_credentialUncheckedUpdateManyWithoutUsersNestedInput
  files?: Prisma.dfw_fileUncheckedUpdateManyWithoutUserNestedInput
}

export type dfw_userCreateWithoutCredentialsInput = {
  id?: string
  name?: string | null
  email?: string | null
  displayName?: string | null
  encodedKey?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  files?: Prisma.dfw_fileCreateNestedManyWithoutUserInput
  sessions?: Prisma.dfw_sessionCreateNestedManyWithoutUserInput
}

export type dfw_userUncheckedCreateWithoutCredentialsInput = {
  id?: string
  name?: string | null
  email?: string | null
  displayName?: string | null
  encodedKey?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  files?: Prisma.dfw_fileUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.dfw_sessionUncheckedCreateNestedManyWithoutUserInput
}

export type dfw_userCreateOrConnectWithoutCredentialsInput = {
  where: Prisma.dfw_userWhereUniqueInput
  create: Prisma.XOR<Prisma.dfw_userCreateWithoutCredentialsInput, Prisma.dfw_userUncheckedCreateWithoutCredentialsInput>
}

export type dfw_userUpsertWithWhereUniqueWithoutCredentialsInput = {
  where: Prisma.dfw_userWhereUniqueInput
  update: Prisma.XOR<Prisma.dfw_userUpdateWithoutCredentialsInput, Prisma.dfw_userUncheckedUpdateWithoutCredentialsInput>
  create: Prisma.XOR<Prisma.dfw_userCreateWithoutCredentialsInput, Prisma.dfw_userUncheckedCreateWithoutCredentialsInput>
}

export type dfw_userUpdateWithWhereUniqueWithoutCredentialsInput = {
  where: Prisma.dfw_userWhereUniqueInput
  data: Prisma.XOR<Prisma.dfw_userUpdateWithoutCredentialsInput, Prisma.dfw_userUncheckedUpdateWithoutCredentialsInput>
}

export type dfw_userUpdateManyWithWhereWithoutCredentialsInput = {
  where: Prisma.dfw_userScalarWhereInput
  data: Prisma.XOR<Prisma.dfw_userUpdateManyMutationInput, Prisma.dfw_userUncheckedUpdateManyWithoutCredentialsInput>
}

export type dfw_userScalarWhereInput = {
  AND?: Prisma.dfw_userScalarWhereInput | Prisma.dfw_userScalarWhereInput[]
  OR?: Prisma.dfw_userScalarWhereInput[]
  NOT?: Prisma.dfw_userScalarWhereInput | Prisma.dfw_userScalarWhereInput[]
  id?: Prisma.StringFilter<"dfw_user"> | string
  name?: Prisma.StringNullableFilter<"dfw_user"> | string | null
  email?: Prisma.StringNullableFilter<"dfw_user"> | string | null
  displayName?: Prisma.StringNullableFilter<"dfw_user"> | string | null
  encodedKey?: Prisma.StringNullableFilter<"dfw_user"> | string | null
  createdAt?: Prisma.DateTimeFilter<"dfw_user"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"dfw_user"> | Date | string
}

export type dfw_userCreateWithoutFilesInput = {
  id?: string
  name?: string | null
  email?: string | null
  displayName?: string | null
  encodedKey?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  credentials?: Prisma.dfw_credentialCreateNestedManyWithoutUsersInput
  sessions?: Prisma.dfw_sessionCreateNestedManyWithoutUserInput
}

export type dfw_userUncheckedCreateWithoutFilesInput = {
  id?: string
  name?: string | null
  email?: string | null
  displayName?: string | null
  encodedKey?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  credentials?: Prisma.dfw_credentialUncheckedCreateNestedManyWithoutUsersInput
  sessions?: Prisma.dfw_sessionUncheckedCreateNestedManyWithoutUserInput
}

export type dfw_userCreateOrConnectWithoutFilesInput = {
  where: Prisma.dfw_userWhereUniqueInput
  create: Prisma.XOR<Prisma.dfw_userCreateWithoutFilesInput, Prisma.dfw_userUncheckedCreateWithoutFilesInput>
}

export type dfw_userUpsertWithoutFilesInput = {
  update: Prisma.XOR<Prisma.dfw_userUpdateWithoutFilesInput, Prisma.dfw_userUncheckedUpdateWithoutFilesInput>
  create: Prisma.XOR<Prisma.dfw_userCreateWithoutFilesInput, Prisma.dfw_userUncheckedCreateWithoutFilesInput>
  where?: Prisma.dfw_userWhereInput
}

export type dfw_userUpdateToOneWithWhereWithoutFilesInput = {
  where?: Prisma.dfw_userWhereInput
  data: Prisma.XOR<Prisma.dfw_userUpdateWithoutFilesInput, Prisma.dfw_userUncheckedUpdateWithoutFilesInput>
}

export type dfw_userUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  credentials?: Prisma.dfw_credentialUpdateManyWithoutUsersNestedInput
  sessions?: Prisma.dfw_sessionUpdateManyWithoutUserNestedInput
}

export type dfw_userUncheckedUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  credentials?: Prisma.dfw_credentialUncheckedUpdateManyWithoutUsersNestedInput
  sessions?: Prisma.dfw_sessionUncheckedUpdateManyWithoutUserNestedInput
}

export type dfw_userUpdateWithoutCredentialsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  files?: Prisma.dfw_fileUpdateManyWithoutUserNestedInput
  sessions?: Prisma.dfw_sessionUpdateManyWithoutUserNestedInput
}

export type dfw_userUncheckedUpdateWithoutCredentialsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  files?: Prisma.dfw_fileUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.dfw_sessionUncheckedUpdateManyWithoutUserNestedInput
}

export type dfw_userUncheckedUpdateManyWithoutCredentialsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  encodedKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type Dfw_userCountOutputType
 */

export type Dfw_userCountOutputType = {
  credentials: number
  files: number
  sessions: number
}

export type Dfw_userCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  credentials?: boolean | Dfw_userCountOutputTypeCountCredentialsArgs
  files?: boolean | Dfw_userCountOutputTypeCountFilesArgs
  sessions?: boolean | Dfw_userCountOutputTypeCountSessionsArgs
}

/**
 * Dfw_userCountOutputType without action
 */
export type Dfw_userCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dfw_userCountOutputType
   */
  select?: Prisma.Dfw_userCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Dfw_userCountOutputType without action
 */
export type Dfw_userCountOutputTypeCountCredentialsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_credentialWhereInput
}

/**
 * Dfw_userCountOutputType without action
 */
export type Dfw_userCountOutputTypeCountFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_fileWhereInput
}

/**
 * Dfw_userCountOutputType without action
 */
export type Dfw_userCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.dfw_sessionWhereInput
}


export type dfw_userSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  displayName?: boolean
  encodedKey?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  credentials?: boolean | Prisma.dfw_user$credentialsArgs<ExtArgs>
  files?: boolean | Prisma.dfw_user$filesArgs<ExtArgs>
  sessions?: boolean | Prisma.dfw_user$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.Dfw_userCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dfw_user"]>

export type dfw_userSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  displayName?: boolean
  encodedKey?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dfw_user"]>

export type dfw_userSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  displayName?: boolean
  encodedKey?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dfw_user"]>

export type dfw_userSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  displayName?: boolean
  encodedKey?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type dfw_userOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "displayName" | "encodedKey" | "createdAt" | "updatedAt", ExtArgs["result"]["dfw_user"]>
export type dfw_userInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  credentials?: boolean | Prisma.dfw_user$credentialsArgs<ExtArgs>
  files?: boolean | Prisma.dfw_user$filesArgs<ExtArgs>
  sessions?: boolean | Prisma.dfw_user$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.Dfw_userCountOutputTypeDefaultArgs<ExtArgs>
}
export type dfw_userIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type dfw_userIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $dfw_userPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "dfw_user"
  objects: {
    credentials: Prisma.$dfw_credentialPayload<ExtArgs>[]
    files: Prisma.$dfw_filePayload<ExtArgs>[]
    sessions: Prisma.$dfw_sessionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string | null
    email: string | null
    displayName: string | null
    encodedKey: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dfw_user"]>
  composites: {}
}

export type dfw_userGetPayload<S extends boolean | null | undefined | dfw_userDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$dfw_userPayload, S>

export type dfw_userCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<dfw_userFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Dfw_userCountAggregateInputType | true
  }

export interface dfw_userDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['dfw_user'], meta: { name: 'dfw_user' } }
  /**
   * Find zero or one Dfw_user that matches the filter.
   * @param {dfw_userFindUniqueArgs} args - Arguments to find a Dfw_user
   * @example
   * // Get one Dfw_user
   * const dfw_user = await prisma.dfw_user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends dfw_userFindUniqueArgs>(args: Prisma.SelectSubset<T, dfw_userFindUniqueArgs<ExtArgs>>): Prisma.Prisma__dfw_userClient<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dfw_user that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {dfw_userFindUniqueOrThrowArgs} args - Arguments to find a Dfw_user
   * @example
   * // Get one Dfw_user
   * const dfw_user = await prisma.dfw_user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends dfw_userFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, dfw_userFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__dfw_userClient<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dfw_user that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_userFindFirstArgs} args - Arguments to find a Dfw_user
   * @example
   * // Get one Dfw_user
   * const dfw_user = await prisma.dfw_user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends dfw_userFindFirstArgs>(args?: Prisma.SelectSubset<T, dfw_userFindFirstArgs<ExtArgs>>): Prisma.Prisma__dfw_userClient<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dfw_user that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_userFindFirstOrThrowArgs} args - Arguments to find a Dfw_user
   * @example
   * // Get one Dfw_user
   * const dfw_user = await prisma.dfw_user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends dfw_userFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, dfw_userFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__dfw_userClient<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Dfw_users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_userFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Dfw_users
   * const dfw_users = await prisma.dfw_user.findMany()
   * 
   * // Get first 10 Dfw_users
   * const dfw_users = await prisma.dfw_user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dfw_userWithIdOnly = await prisma.dfw_user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends dfw_userFindManyArgs>(args?: Prisma.SelectSubset<T, dfw_userFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dfw_user.
   * @param {dfw_userCreateArgs} args - Arguments to create a Dfw_user.
   * @example
   * // Create one Dfw_user
   * const Dfw_user = await prisma.dfw_user.create({
   *   data: {
   *     // ... data to create a Dfw_user
   *   }
   * })
   * 
   */
  create<T extends dfw_userCreateArgs>(args: Prisma.SelectSubset<T, dfw_userCreateArgs<ExtArgs>>): Prisma.Prisma__dfw_userClient<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Dfw_users.
   * @param {dfw_userCreateManyArgs} args - Arguments to create many Dfw_users.
   * @example
   * // Create many Dfw_users
   * const dfw_user = await prisma.dfw_user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends dfw_userCreateManyArgs>(args?: Prisma.SelectSubset<T, dfw_userCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Dfw_users and returns the data saved in the database.
   * @param {dfw_userCreateManyAndReturnArgs} args - Arguments to create many Dfw_users.
   * @example
   * // Create many Dfw_users
   * const dfw_user = await prisma.dfw_user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Dfw_users and only return the `id`
   * const dfw_userWithIdOnly = await prisma.dfw_user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends dfw_userCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, dfw_userCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Dfw_user.
   * @param {dfw_userDeleteArgs} args - Arguments to delete one Dfw_user.
   * @example
   * // Delete one Dfw_user
   * const Dfw_user = await prisma.dfw_user.delete({
   *   where: {
   *     // ... filter to delete one Dfw_user
   *   }
   * })
   * 
   */
  delete<T extends dfw_userDeleteArgs>(args: Prisma.SelectSubset<T, dfw_userDeleteArgs<ExtArgs>>): Prisma.Prisma__dfw_userClient<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dfw_user.
   * @param {dfw_userUpdateArgs} args - Arguments to update one Dfw_user.
   * @example
   * // Update one Dfw_user
   * const dfw_user = await prisma.dfw_user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends dfw_userUpdateArgs>(args: Prisma.SelectSubset<T, dfw_userUpdateArgs<ExtArgs>>): Prisma.Prisma__dfw_userClient<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Dfw_users.
   * @param {dfw_userDeleteManyArgs} args - Arguments to filter Dfw_users to delete.
   * @example
   * // Delete a few Dfw_users
   * const { count } = await prisma.dfw_user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends dfw_userDeleteManyArgs>(args?: Prisma.SelectSubset<T, dfw_userDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dfw_users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_userUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Dfw_users
   * const dfw_user = await prisma.dfw_user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends dfw_userUpdateManyArgs>(args: Prisma.SelectSubset<T, dfw_userUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dfw_users and returns the data updated in the database.
   * @param {dfw_userUpdateManyAndReturnArgs} args - Arguments to update many Dfw_users.
   * @example
   * // Update many Dfw_users
   * const dfw_user = await prisma.dfw_user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Dfw_users and only return the `id`
   * const dfw_userWithIdOnly = await prisma.dfw_user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends dfw_userUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, dfw_userUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Dfw_user.
   * @param {dfw_userUpsertArgs} args - Arguments to update or create a Dfw_user.
   * @example
   * // Update or create a Dfw_user
   * const dfw_user = await prisma.dfw_user.upsert({
   *   create: {
   *     // ... data to create a Dfw_user
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dfw_user we want to update
   *   }
   * })
   */
  upsert<T extends dfw_userUpsertArgs>(args: Prisma.SelectSubset<T, dfw_userUpsertArgs<ExtArgs>>): Prisma.Prisma__dfw_userClient<runtime.Types.Result.GetResult<Prisma.$dfw_userPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Dfw_users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_userCountArgs} args - Arguments to filter Dfw_users to count.
   * @example
   * // Count the number of Dfw_users
   * const count = await prisma.dfw_user.count({
   *   where: {
   *     // ... the filter for the Dfw_users we want to count
   *   }
   * })
  **/
  count<T extends dfw_userCountArgs>(
    args?: Prisma.Subset<T, dfw_userCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Dfw_userCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dfw_user.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Dfw_userAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Dfw_userAggregateArgs>(args: Prisma.Subset<T, Dfw_userAggregateArgs>): Prisma.PrismaPromise<GetDfw_userAggregateType<T>>

  /**
   * Group by Dfw_user.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {dfw_userGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends dfw_userGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: dfw_userGroupByArgs['orderBy'] }
      : { orderBy?: dfw_userGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, dfw_userGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDfw_userGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the dfw_user model
 */
readonly fields: dfw_userFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for dfw_user.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__dfw_userClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  credentials<T extends Prisma.dfw_user$credentialsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.dfw_user$credentialsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_credentialPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  files<T extends Prisma.dfw_user$filesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.dfw_user$filesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_filePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  sessions<T extends Prisma.dfw_user$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.dfw_user$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$dfw_sessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the dfw_user model
 */
export interface dfw_userFieldRefs {
  readonly id: Prisma.FieldRef<"dfw_user", 'String'>
  readonly name: Prisma.FieldRef<"dfw_user", 'String'>
  readonly email: Prisma.FieldRef<"dfw_user", 'String'>
  readonly displayName: Prisma.FieldRef<"dfw_user", 'String'>
  readonly encodedKey: Prisma.FieldRef<"dfw_user", 'String'>
  readonly createdAt: Prisma.FieldRef<"dfw_user", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"dfw_user", 'DateTime'>
}
    

// Custom InputTypes
/**
 * dfw_user findUnique
 */
export type dfw_userFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  /**
   * Filter, which dfw_user to fetch.
   */
  where: Prisma.dfw_userWhereUniqueInput
}

/**
 * dfw_user findUniqueOrThrow
 */
export type dfw_userFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  /**
   * Filter, which dfw_user to fetch.
   */
  where: Prisma.dfw_userWhereUniqueInput
}

/**
 * dfw_user findFirst
 */
export type dfw_userFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  /**
   * Filter, which dfw_user to fetch.
   */
  where?: Prisma.dfw_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_users to fetch.
   */
  orderBy?: Prisma.dfw_userOrderByWithRelationInput | Prisma.dfw_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dfw_users.
   */
  cursor?: Prisma.dfw_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dfw_users.
   */
  distinct?: Prisma.Dfw_userScalarFieldEnum | Prisma.Dfw_userScalarFieldEnum[]
}

/**
 * dfw_user findFirstOrThrow
 */
export type dfw_userFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  /**
   * Filter, which dfw_user to fetch.
   */
  where?: Prisma.dfw_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_users to fetch.
   */
  orderBy?: Prisma.dfw_userOrderByWithRelationInput | Prisma.dfw_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for dfw_users.
   */
  cursor?: Prisma.dfw_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of dfw_users.
   */
  distinct?: Prisma.Dfw_userScalarFieldEnum | Prisma.Dfw_userScalarFieldEnum[]
}

/**
 * dfw_user findMany
 */
export type dfw_userFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  /**
   * Filter, which dfw_users to fetch.
   */
  where?: Prisma.dfw_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of dfw_users to fetch.
   */
  orderBy?: Prisma.dfw_userOrderByWithRelationInput | Prisma.dfw_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing dfw_users.
   */
  cursor?: Prisma.dfw_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` dfw_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` dfw_users.
   */
  skip?: number
  distinct?: Prisma.Dfw_userScalarFieldEnum | Prisma.Dfw_userScalarFieldEnum[]
}

/**
 * dfw_user create
 */
export type dfw_userCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  /**
   * The data needed to create a dfw_user.
   */
  data: Prisma.XOR<Prisma.dfw_userCreateInput, Prisma.dfw_userUncheckedCreateInput>
}

/**
 * dfw_user createMany
 */
export type dfw_userCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many dfw_users.
   */
  data: Prisma.dfw_userCreateManyInput | Prisma.dfw_userCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dfw_user createManyAndReturn
 */
export type dfw_userCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * The data used to create many dfw_users.
   */
  data: Prisma.dfw_userCreateManyInput | Prisma.dfw_userCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * dfw_user update
 */
export type dfw_userUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  /**
   * The data needed to update a dfw_user.
   */
  data: Prisma.XOR<Prisma.dfw_userUpdateInput, Prisma.dfw_userUncheckedUpdateInput>
  /**
   * Choose, which dfw_user to update.
   */
  where: Prisma.dfw_userWhereUniqueInput
}

/**
 * dfw_user updateMany
 */
export type dfw_userUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update dfw_users.
   */
  data: Prisma.XOR<Prisma.dfw_userUpdateManyMutationInput, Prisma.dfw_userUncheckedUpdateManyInput>
  /**
   * Filter which dfw_users to update
   */
  where?: Prisma.dfw_userWhereInput
  /**
   * Limit how many dfw_users to update.
   */
  limit?: number
}

/**
 * dfw_user updateManyAndReturn
 */
export type dfw_userUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * The data used to update dfw_users.
   */
  data: Prisma.XOR<Prisma.dfw_userUpdateManyMutationInput, Prisma.dfw_userUncheckedUpdateManyInput>
  /**
   * Filter which dfw_users to update
   */
  where?: Prisma.dfw_userWhereInput
  /**
   * Limit how many dfw_users to update.
   */
  limit?: number
}

/**
 * dfw_user upsert
 */
export type dfw_userUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  /**
   * The filter to search for the dfw_user to update in case it exists.
   */
  where: Prisma.dfw_userWhereUniqueInput
  /**
   * In case the dfw_user found by the `where` argument doesn't exist, create a new dfw_user with this data.
   */
  create: Prisma.XOR<Prisma.dfw_userCreateInput, Prisma.dfw_userUncheckedCreateInput>
  /**
   * In case the dfw_user was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.dfw_userUpdateInput, Prisma.dfw_userUncheckedUpdateInput>
}

/**
 * dfw_user delete
 */
export type dfw_userDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
  /**
   * Filter which dfw_user to delete.
   */
  where: Prisma.dfw_userWhereUniqueInput
}

/**
 * dfw_user deleteMany
 */
export type dfw_userDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which dfw_users to delete
   */
  where?: Prisma.dfw_userWhereInput
  /**
   * Limit how many dfw_users to delete.
   */
  limit?: number
}

/**
 * dfw_user.credentials
 */
export type dfw_user$credentialsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_credential
   */
  select?: Prisma.dfw_credentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_credential
   */
  omit?: Prisma.dfw_credentialOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_credentialInclude<ExtArgs> | null
  where?: Prisma.dfw_credentialWhereInput
  orderBy?: Prisma.dfw_credentialOrderByWithRelationInput | Prisma.dfw_credentialOrderByWithRelationInput[]
  cursor?: Prisma.dfw_credentialWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Dfw_credentialScalarFieldEnum | Prisma.Dfw_credentialScalarFieldEnum[]
}

/**
 * dfw_user.files
 */
export type dfw_user$filesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_file
   */
  select?: Prisma.dfw_fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_file
   */
  omit?: Prisma.dfw_fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_fileInclude<ExtArgs> | null
  where?: Prisma.dfw_fileWhereInput
  orderBy?: Prisma.dfw_fileOrderByWithRelationInput | Prisma.dfw_fileOrderByWithRelationInput[]
  cursor?: Prisma.dfw_fileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Dfw_fileScalarFieldEnum | Prisma.Dfw_fileScalarFieldEnum[]
}

/**
 * dfw_user.sessions
 */
export type dfw_user$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_session
   */
  select?: Prisma.dfw_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_session
   */
  omit?: Prisma.dfw_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_sessionInclude<ExtArgs> | null
  where?: Prisma.dfw_sessionWhereInput
  orderBy?: Prisma.dfw_sessionOrderByWithRelationInput | Prisma.dfw_sessionOrderByWithRelationInput[]
  cursor?: Prisma.dfw_sessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Dfw_sessionScalarFieldEnum | Prisma.Dfw_sessionScalarFieldEnum[]
}

/**
 * dfw_user without action
 */
export type dfw_userDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the dfw_user
   */
  select?: Prisma.dfw_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the dfw_user
   */
  omit?: Prisma.dfw_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.dfw_userInclude<ExtArgs> | null
}
